Appsco/appsco-front

src/application/appsco-application-components-page.html, src/application/appsco-application-settings-page.html, src/appsco-app.html, src/appsco-applications-page.html
=> DASH-1873 appsco-front component

src/application/appsco-application-settings-page.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-applications-page.html
=> DASH-1873 appsco-applications-page, share, filters

src/application/appsco-application-settings-page.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-applications-page.html
=> DASH-1873 application-item adjustment

src/application/appsco-application-components-page.html, src/application/appsco-application-log-page.html, src/application/appsco-application-page-actions.html, src/application/appsco-application-subscribers-page.html, src/application/appsco-applications-page-actions.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-applications-page.html, src/shared-styles.html
=> DASH-1873 Responsive style. Removed unnecessary imports.

src/application/appsco-application-components-page.html, src/application/appsco-home-page-actions.html, src/appsco-app.html, src/appsco-home-page.html
=> DASH-1873 Applications page renamed to Home

src/account/appsco-account-2fa-page.html, src/account/appsco-account-authorized-apps-page.html, src/account/appsco-account-change-password-page.html, src/account/appsco-account-components-page.html, src/account/appsco-account-log-page.html, src/account/appsco-account-notifications-page.html, src/account/appsco-account-page-actions.html, src/account/appsco-account-settings-page.html, src/account/appsco-account-transfer-token-page.html, src/application/appsco-application-components-page.html, src/application/appsco-application-log-page.html, src/application/appsco-application-settings-page.html, src/application/appsco-application-subscribers-page.html, src/appsco-account-page.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-home-page.html, src/shared-styles.html
=> DASH-1873 appsco-account-page

src/account/appsco-account-components-page.html, src/account/appsco-account-page-actions.html, src/application/appsco-application-components-page.html, src/application/appsco-home-page-actions.html, src/appsco-app.html, src/appsco-home-page.html
=> DASH-1873 appsco-front new design

src/account/appsco-account-authorized-apps-page.html, src/account/appsco-account-components-page.html, src/account/appsco-account-log-page.html, src/account/appsco-account-page-actions.html, src/account/appsco-account-settings-page.html, src/application/appsco-application-components-page.html, src/appsco-account-page.html, src/appsco-app.html
=> DASH-1873 appsco-account components

src/account/appsco-account-authorized-apps-page.html, src/account/appsco-account-components-page.html, src/appsco-account-page.html, src/appsco-app.html
=> DASH-1873 appsco-account-authorized-apps update

src/account/appsco-account-components-page.html, src/account/appsco-account-page-actions.html, src/application/appsco-home-page-actions.html, src/appsco-account-page.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-home-page.html, src/shared-styles.html
=> DASH-1873 See All notifications action and Advanced Settings enable/disable

src/account/appsco-account-2fa-page.html, src/account/appsco-account-authorized-apps-page.html, src/account/appsco-account-change-password-page.html, src/account/appsco-account-components-page.html, src/account/appsco-account-log-page.html, src/account/appsco-account-notifications-page.html, src/account/appsco-account-page-actions.html, src/account/appsco-account-settings-page.html, src/account/appsco-account-transfer-token-page.html, src/application/appsco-application-components-page.html, src/application/appsco-application-log-page.html, src/application/appsco-application-settings-page.html, src/application/appsco-application-subscribers-page.html, src/appsco-account-page.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-home-page.html, src/appsco-not-found-page.html, src/webkit-scrollbar-style.html
=> DASH-1873 pages update

src/application/appsco-application-components-page.html, src/appsco-app.html, src/appsco-home-page.html
https://webcomputing.jira.com/browse/DASH-1885
=> DASH-1885 update autologin

src/account/appsco-account-authorized-apps-page.html, src/account/appsco-account-log-page.html, src/account/appsco-account-notifications-page.html, src/account/appsco-account-page-actions.html, src/application/appsco-application-components-page.html, src/application/appsco-application-log-page.html, src/application/appsco-application-subscribers-page.html, src/application/appsco-home-page-actions.html, src/appsco-404-page.html, src/appsco-account-page.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-home-page.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-1885
=> DASH-1885 polishing front

src/account/appsco-account-components-page.html, src/appsco-account-page.html, src/appsco-app.html, src/appsco-application-page.html
https://webcomputing.jira.com/browse/DASH-1885
=> DASH-1885 application-page: load application on page refresh

src/application/appsco-home-page-actions.html, src/appsco-home-page.html
https://webcomputing.jira.com/browse/DASH-1885
=> DASH-1885 style for smaller screens

src/appsco-app.html, src/appsco-vault-page.html, src/vault/appsco-vault-manage-item.html
https://webcomputing.jira.com/browse/DASH-1850
=> DASH-1850 appsco-vault-items-page

src/appsco-app.html, src/vault/appsco-vault-manage-item.html, src/vault/appsco-vault-page-actions.html
https://webcomputing.jira.com/browse/DASH-1850
=> DASH-1850 add vault item actions

src/account/appsco-account-2fa-page.html, src/account/appsco-account-components-page.html, src/application/appsco-application-components-page.html, src/application/appsco-application-log-page.html, src/appsco-account-page.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-home-page.html, src/appsco-vault-page.html, src/vault/appsco-vault-manage-item.html
https://webcomputing.jira.com/browse/DASH-1891
=> DASH-1891 appsco-application-log: mixin names fixed

src/appsco-app.html, src/vault/appsco-vault-manage-item.html
https://webcomputing.jira.com/browse/DASH-1891
=> paper-dialog responsive

index.html, src/application/appsco-home-page-actions.html, src/appsco-app.html, src/appsco-home-page.html
https://webcomputing.jira.com/browse/DASH-1897
=> DASH-1897 appsco-application-actions support

src/appsco-404-page.html, src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-1894
=> DASH-1894 404 page design

src/appsco-upgrade-page.html
https://webcomputing.jira.com/browse/DASH-1921
=> DASH-1921 upgrade page style fix

src/appsco-upgrade-page.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-1921
=> DASH-1921 Upgrade page style

src/applications/appsco-applications-page-actions.html, src/appsco-app.html, src/appsco-applications-page.html
https://webcomputing.jira.com/browse/DASH-1895
=> DASH-1895 appsco-applications-page (management)

src/appsco-app.html, src/appsco-applications-page.html, src/appsco-home-page.html
https://webcomputing.jira.com/browse/DASH-1923
=> DASH-1923 [appsco-applications] appsco-company-application-add

src/appsco-app.html, src/appsco-applications-page.html
https://webcomputing.jira.com/browse/DASH-1925
=> DASH-1925 appsco-application-orgunit

src/application/appsco-application-log-page.html, src/application/appsco-application-subscribers-page.html, src/application/appsco-home-page-actions.html, src/applications/appsco-application-orgunits-page.html, src/applications/appsco-application-sharing-settings-page.html, src/applications/appsco-manage-application-components-page.html, src/applications/appsco-manage-application-page-actions.html, src/appsco-app.html, src/appsco-applications-page.html, src/appsco-home-page.html, src/appsco-manage-application-page.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-1908
=> DASH-1908 appsco-application-page (management)

index.html, src/applications/appsco-application-assignees-page.html, src/applications/appsco-manage-application-components-page.html, src/appsco-app.html, src/appsco-applications-page.html, src/appsco-manage-application-page.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-1908
=> DASH-1908 appsco-manage-application-page: support for application assignees

src/account/appsco-account-log-page.html, src/account/appsco-account-notifications-page.html, src/application/appsco-home-page-actions.html, src/appsco-account-page.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-applications-page.html, src/appsco-directory-page.html, src/appsco-home-page.html, src/appsco-manage-account-page.html, src/appsco-manage-application-page.html, src/directory/appsco-directory-add-account.html, src/directory/appsco-directory-import-accounts.html, src/directory/appsco-manage-account-components-page.html, src/directory/appsco-manage-account-page-actions.html, src/shared-styles.html, src/vault/appsco-vault-page-actions.html
https://webcomputing.jira.com/browse/DASH-1931
=> DASH-1931 appsco-directory-page

index.html, src/application/appsco-application-subscribers-page.html, src/appsco-account-page.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-applications-page.html, src/appsco-billing-page.html, src/appsco-directory-page.html, src/appsco-home-page.html, src/appsco-manage-account-page.html, src/appsco-manage-application-page.html, src/billing/appsco-billing-invoice.html, src/billing/appsco-billing-page-actions.html, src/billing/appsco-credit-card.html, src/billing/appsco-subscription-cancel.html, src/directory/appsco-account-orgunits-page.html, src/directory/appsco-manage-account-components-page.html, src/shared-styles.html, src/upgrade/appsco-upgrade-action.html
https://webcomputing.jira.com/browse/DASH-1945
=> DASH-1945 appsco-billing-page

src/applications/appsco-application-assignees-page.html, src/appsco-app.html, src/appsco-applications-page.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-1962
=> DASH-1962 appsco-application: load subscribers and log

src/appsco-billing-page.html
https://webcomputing.jira.com/browse/DASH-1966
=> DASH-1966 Appsco Business / Billing -> Instead of Size rename to Appsco Licenses

src/application/appsco-application-log-page.html, src/applications/appsco-manage-application-components-page.html, src/appsco-app.html, src/appsco-applications-page.html, src/appsco-manage-application-page.html, src/billing/appsco-credit-card.html, src/billing/appsco-subscription-cancel.html, src/directory/appsco-directory-add-account.html, src/directory/appsco-directory-import-accounts.html, src/shared-styles.html, src/upgrade/appsco-upgrade-action.html, src/vault/appsco-vault-manage-item.html
https://webcomputing.jira.com/browse/DASH-1973
=> DASH-1973 paper-dialog-scrollable: scroll is always present

index.html
https://webcomputing.jira.com/browse/DASH-1978
=> DASH-1978 Add favicon and rename "My App"

src/appsco-manage-account-page.html
https://webcomputing.jira.com/browse/DASH-1984
=> DASH-1984 Appsco account - set initials instead of picture

src/appsco-billing-page.html
https://webcomputing.jira.com/browse/DASH-1966
=> DASH-1966 Billing page: Licenses label to Quantity

src/appsco-billing-page.html
https://webcomputing.jira.com/browse/DASH-1966
=> Appsco identities changed to Appsco Licenses

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-1963
=> DASH-1963 Unable to add custom item

src/appsco-applications-page.html, src/appsco-directory-page.html
https://webcomputing.jira.com/browse/DASH-1988
=> DASH-1988 [Company] Filter applications and accounts by organization unit

index.html, src/account/appsco-account-change-password-page.html, src/appsco-app.html, src/appsco-manage-account-page.html
https://webcomputing.jira.com/browse/DASH-1977
=> DASH-1977 Directory/User/Change Password old password filed remove

src/application/appsco-application-components-page.html, src/application/appsco-application-subscribers-page.html, src/appsco-application-page.html, src/appsco-applications-page.html, src/appsco-home-page.html, src/appsco-manage-application-page.html
https://webcomputing.jira.com/browse/DASH-1984
=> DASH-1984 Initials set on subscribers

src/appsco-billing-page.html
https://webcomputing.jira.com/browse/DASH-1989
=> DASH-1989 [Company] Billing page when company is created

src/appsco-app.html, src/appsco-manage-account-page.html, src/directory/appsco-manage-account-change-password-page.html
https://webcomputing.jira.com/browse/DASH-1977
=> DASH-1977 password change for company account

src/appsco-app.html, src/directory/appsco-manage-account-components-page.html
https://webcomputing.jira.com/browse/DASH-1997
=> DASH-1997 I can not find anywhere to make a user an administrator

src/account/appsco-account-authorized-apps-page.html, src/appsco-account-page.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-applications-page.html, src/appsco-company-settings-page.html, src/appsco-directory-page.html, src/appsco-home-page.html
https://webcomputing.jira.com/browse/DASH-1990
=> DASH-1990 Update account log with new log types

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2000
=> DASH-2000 Refreshing a page always sends you to home

src/appsco-company-settings-page.html, src/company/appsco-company-image-settings.html, src/directory/appsco-directory-add-account.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2005
=> DASH-2005 Company logo change not working in FF

src/appsco-home-page.html
https://webcomputing.jira.com/browse/DASH-1995
=> DASH-1955 Revoke action should not be visible on company application

src/appsco-app.html, src/appsco-logout-page.html
https://webcomputing.jira.com/browse/DASH-1981
=> DASH-1981 Brief 404 error when logging out

src/appsco-app.html, src/appsco-billing-page.html, src/appsco-company-settings-page.html, src/directory/appsco-directory-add-account.html
https://webcomputing.jira.com/browse/DASH-2024
=> DASH-2024 [Billing] UX Improvements

src/appsco-upgrade-page.html
https://webcomputing.jira.com/browse/DASH-2026
=> DASH-2026 [Upgrade to business] Add loader on Upgrade action

polymer.json, src/appsco-app.html, src/appsco-audit-log-page.html, src/auditlog/appsco-audit-log-page-actions.html, src/auditlog/appsco-audit-log.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2002
=> DASH-2002 Create Audit log page

src/appsco-audit-log-page.html
https://webcomputing.jira.com/browse/DASH-2002
=> DASH-2002 Audit log improvement

bower.json, polymer.json, src/appsco-app.html, src/appsco-statistics-page.html
https://webcomputing.jira.com/browse/DASH-2023
=> DASH-2023 Create Statistics page

src/appsco-statistics-page.html
https://webcomputing.jira.com/browse/DASH-2023
=> DASH-2023 Show meesages if there are no data

src/appsco-app.html, src/appsco-home-page.html, src/appsco-statistics-page.html, src/appsco-vault-page.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2050
=> DASH-2050 [Statistics] Case when new company is created

src/appsco-statistics-page.html
https://webcomputing.jira.com/browse/DASH-2050
=> DASH-2050 [Statistics] Case when new company is created - improvements

src/application/appsco-home-page-actions.html, src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2073
=> DASH-2073 Create dashboard if private does not exist

src/appsco-app.html, src/appsco-audit-log-page.html, src/appsco-statistics-page.html, src/auditlog/appsco-audit-log.html
https://webcomputing.jira.com/browse/DASH-2072
=> DASH-2072 Statistics - Application usage

src/appsco-company-settings-page.html, src/appsco-manage-account-page.html
https://webcomputing.jira.com/browse/DASH-2087
=> DASH-2087 Saving company with empty name results in hang

src/application/appsco-home-page-actions.html, src/applications/appsco-applications-page-actions.html, src/appsco-app.html, src/appsco-applications-page.html, src/appsco-directory-page.html, src/appsco-home-page.html, src/directory/appsco-directory-page-actions.html
https://webcomputing.jira.com/browse/DASH-2037
=> DASH-2037 Filter applications + select applications bug

src/appsco-app.html, src/appsco-directory-page.html
https://webcomputing.jira.com/browse/DASH-2090
=> DASH-2090 Applications assigned through org units not updating at home page

src/appsco-statistics-page.html
https://webcomputing.jira.com/browse/DASH-2092
=> DASH-2092 [Statistics] Two-factor authentication pie chart error

src/appsco-application-page.html, src/appsco-applications-page.html, src/appsco-manage-account-page.html, src/appsco-manage-application-page.html
https://webcomputing.jira.com/browse/DASH-2093
=> DASH-2093 Manage Account, Manage Application page reload

src/appsco-app.html, src/appsco-directory-page.html
https://webcomputing.jira.com/browse/DASH-2095
=> DASH-2095 [Directory page] Select account plus filtering improvements

src/appsco-app.html, src/appsco-directory-page.html, src/directory/appsco-directory-actions.html, src/directory/appsco-directory-page-actions.html
https://webcomputing.jira.com/browse/DASH-2099
=> DASH-2099 [Directory Page] Reset page actions to default state

src/appsco-account-page.html, src/appsco-application-page.html, src/appsco-audit-log-page.html, src/appsco-manage-account-page.html, src/appsco-manage-application-page.html, src/auditlog/appsco-audit-log.html
https://webcomputing.jira.com/browse/DASH-2102
=> DASH-2102 [Audit Page] Make event type list searchable

src/application/appsco-application-subscribers-page.html, src/applications/appsco-application-assignees-page.html, src/appsco-billing-page.html, src/auditlog/appsco-audit-log.html, src/directory/appsco-directory-role-applications-page.html, src/directory/appsco-directory-role-applications.html
https://webcomputing.jira.com/browse/DASH-2101
=> DASH-2101 Make faster lists loading within pages

src/appsco-app.html, src/appsco-provisioning-settings-page.html, src/provisioning/appsco-integration-item.html, src/provisioning/appsco-integration-items.html, src/provisioning/appsco-integration-page.html, src/provisioning/appsco-synced-accounts-page.html
https://webcomputing.jira.com/browse/DASH-2082
=> DASH-2082 Integration sync improvements

src/appsco-applications-page.html, src/appsco-directory-page.html
https://webcomputing.jira.com/browse/DASH-2078
=> DASH-2078 Org structure. Need more than 3 levels.

src/application/appsco-application-page-actions.html, src/application/appsco-application-subscribers-page.html, src/applications/appsco-application-assignees-page.html, src/applications/appsco-manage-application-page-actions.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-applications-page.html, src/appsco-manage-application-page.html, src/directory/appsco-directory-actions.html
https://webcomputing.jira.com/browse/DASH-2058
=> DASH-2058 Implement search on assignees list - frontend

src/appsco-applications-page.html, src/appsco-home-page.html
https://webcomputing.jira.com/browse/DASH-2119
=> DASH-2119 [Applications] Search Applications by term

src/application/appsco-application-settings-dialog.html, src/appsco-app.html, src/appsco-home-page.html
https://webcomputing.jira.com/browse/DASH-2137
=> DASH-2137 Edit credentials button on Free users apps

src/appsco-app.html, src/appsco-provisioning-settings-page.html, src/provisioning/appsco-integration-page.html, src/provisioning/appsco-provisioning-settings-page-actions.html
https://webcomputing.jira.com/browse/DASH-2143
=> DASH-2143 [Provisioning] Page actions show / hide animation

src/appsco-provisioning-settings-page.html, src/provisioning/appsco-integration-item.html, src/provisioning/appsco-integration-page.html, src/provisioning/appsco-provisioning-settings-page-actions.html
https://webcomputing.jira.com/browse/DASH-2082
=> Doble bulk sync problem fixed

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2144
=> DASH-2144 [Front] Move Vault access to top

src/appsco-app.html, src/appsco-directory-page.html, src/directory/appsco-directory-actions.html, src/directory/appsco-directory-page-actions.html, src/directory/appsco-subscription-info-dropdown.html
https://webcomputing.jira.com/browse/DASH-2151
=> DASH-2151 [Front][Directory]Info when maximum user count is reached

src/directory/appsco-directory-actions.html
https://webcomputing.jira.com/browse/DASH-2151
=> DASH-2151 Firefox toggle info fixed

src/appsco-app.html, src/appsco-audit-log-page.html
https://webcomputing.jira.com/browse/DASH-2134
=> DASH-2134 [Front] Searchable drop-down if user is admin in multiple companies

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2181
=> DASH-2181 [Business]Unable to add user to org unit.

src/appsco-app.html, src/appsco-applications-page.html
https://webcomputing.jira.com/browse/DASH-2177
=> DASH-2177 [Personal] Application info sending to 404

bower.json, src/application/appsco-home-page-actions.html, src/applications/appsco-applications-page-actions.html, src/appsco-app.html, src/appsco-audit-log-page.html, src/appsco-company-page.html, src/company/appsco-company-brand-details.html, src/company/appsco-company-brand-settings-page.html, src/company/appsco-company-brand-settings.html, src/company/appsco-company-components-page.html, src/company/appsco-company-home-page-actions.html, src/company/appsco-company-image-settings.html, src/directory/appsco-directory-actions.html, src/directory/appsco-directory-page-actions.html, src/shared-styles.html, src/vault/appsco-vault-page-actions.html
https://webcomputing.jira.com/browse/DASH-2153
=> DASH-2153 [Front][Settings] Create Manage screen for branding company

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2212
=> DASH-2212 [Business] Applications update after sharing

src/appsco-app.html, src/appsco-company-home-page.html
https://webcomputing.jira.com/browse/DASH-2220
=> DASH-2220 [Business] Update changes on users for Directory page

src/appsco-app.html, src/appsco-directory-page.html, src/directory/appsco-directory-add-account.html
https://webcomputing.jira.com/browse/DASH-2207
=> DASH-2207 [Frontend][Directory] Implement design for users invited to company

src/appsco-app.html, src/company/appsco-company-brand-details.html, src/directory/appsco-directory-actions.html, src/directory/appsco-directory-page-actions.html
https://webcomputing.jira.com/browse/DASH-2226
=> DASH-2226 Issues after removing org-unit

src/appsco-app.html, src/provisioning/appsco-provisioning-settings-page-actions.html
https://webcomputing.jira.com/browse/DASH-2276
=> DASH-2276 No link or custom application for company applications

src/appsco-app.html, src/directory/appsco-directory-add-account.html
https://webcomputing.jira.com/browse/DASH-2287
=> DASH-2287 [Frontend][Directory] Unable to add existing user

src/application/appsco-application-page-actions.html, src/application/appsco-home-page-actions.html, src/applications/appsco-manage-application-page-actions.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-audit-log-page.html, src/appsco-manage-application-page.html, src/auditlog/appsco-audit-log.html, src/directory/appsco-directory-actions.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2253
=> DASH-2253 [Frontend] Improve input search field event through project

src/directory/appsco-directory-import-accounts.html
https://webcomputing.jira.com/browse/DASH-2278
=> DASH-2278 [Frontend][Directory] Example .csv Incorrect file type

src/appsco-app.html, src/appsco-company-home-page.html, src/company/appsco-company-home-page-actions.html
https://webcomputing.jira.com/browse/DASH-2283
=> DASH-2283 Add Filter of applications in dashboard home also to business like personal

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2314
=> DASH-2314 Company Apps does not show up on dashboard without page reload

src/appsco-app.html, src/appsco-application-page.html, src/appsco-manage-account-page.html, src/appsco-manage-application-page.html
https://webcomputing.jira.com/browse/DASH-2300
=> DASH-2300 [Business] Unable to load assigness

src/account/appsco-account-change-password-page.html, src/account/appsco-account-page-actions.html, src/account/appsco-account-settings-page.html, src/application/appsco-application-page-actions.html, src/application/appsco-application-settings-dialog.html, src/application/appsco-application-settings-page.html, src/applications/appsco-applications-page-actions.html, src/applications/appsco-manage-application-page-actions.html, src/appsco-app.html, src/appsco-applications-page.html, src/appsco-directory-page.html, src/billing/appsco-billing-invoice.html, src/billing/appsco-billing-send-invoice.html, src/company/appsco-company-brand-settings-page.html, src/company/appsco-company-brand-settings.html, src/company/appsco-company-settings-page.html, src/company/appsco-company-settings.html, src/directory/appsco-manage-account-change-password-page.html, src/directory/appsco-manage-account-page-actions.html, src/provisioning/appsco-provisioning-settings-page-actions.html, src/shared-styles.html, src/upgrade/appsco-upgrade-action.html
https://webcomputing.jira.com/browse/DASH-2272
=> DASH-2272 Implement branding text colours when card is selected

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2329
=> DASH-2329 [Frontend][Account log] Fix log type for remove role from organization unit

src/application/appsco-application-settings-dialog.html
https://webcomputing.jira.com/browse/DASH-2272
=> DASH-2272 Application claims settings dialog button fixed

src/appsco-app.html, src/appsco-applications-page.html, src/appsco-directory-page.html
https://webcomputing.jira.com/browse/DASH-2333
=> DASH-2333 [Frontend] Applications and directory roles get mixed up

src/application/appsco-application-subscribers-page.html, src/applications/appsco-application-assignees-page.html, src/appsco-app.html, src/appsco-company-page.html, src/appsco-directory-page.html, src/company/appsco-company-add-domain.html, src/company/appsco-company-components-page.html, src/company/appsco-company-domain-item.html, src/company/appsco-company-domain-token.html, src/company/appsco-company-domains-page.html, src/company/appsco-company-domains.html, src/company/appsco-company-page-actions.html, src/company/appsco-company-remove-domain.html, src/directory/appsco-directory-actions.html, src/directory/appsco-directory-page-actions.html, src/directory/appsco-info-dropdown.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2196
=> DASH-2196 [Frontend][Company settings] Domains feature support

src/application/appsco-home-page-actions.html, src/applications/appsco-applications-page-actions.html, src/appsco-app.html, src/directory/appsco-directory-actions.html, src/directory/appsco-directory-page-actions.html
https://webcomputing.jira.com/browse/DASH-2124
=> DASH-2124 Add resource action

src/appsco-manage-account-page.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2231
=> DASH-2231 [Frontend][Directory] Disable edit action for user without managed domain

src/appsco-directory-page.html
https://webcomputing.jira.com/browse/DASH-2230
=> DASH-2230 [Frontend][Directory] Show info about verification of managed domain

src/appsco-app.html, src/appsco-directory-page.html, src/directory/appsco-directory-import-accounts.html, src/directory/appsco-directory-page-actions.html
https://webcomputing.jira.com/browse/DASH-2274
=> DASH-2274 [Frontend][Directory] Import users - maximum users limit notification

src/application/appsco-home-page-actions.html, src/applications/appsco-applications-page-actions.html, src/appsco-app.html, src/directory/appsco-directory-actions.html, src/directory/appsco-directory-page-actions.html
Reverts Appsco/appsco-front#136
=> Revert "DASH-2124 Add resource action"

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2356
=> DASH-2356 Company settings - Second company branding colors

src/appsco-directory-page.html, src/directory/appsco-directory-page-actions.html, src/directory/appsco-manage-account-page-actions.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2361
=> DASH-2361 [Frontend][Director] - Add account and import buttons gone

src/company/appsco-company-domain-token.html
https://webcomputing.jira.com/browse/DASH-2366
=> DASH-2366 [Frontend][Company Settings] Domain verification info

src/company/appsco-company-domain-item.html
https://webcomputing.jira.com/browse/DASH-2358
=> DASH-2358 [Frontend] Verified domain summary bug

src/appsco-directory-page.html
https://webcomputing.jira.com/browse/DASH-2335
=> DASH-2335 [Frontend][Directory] Licence mandatory for invite user to company

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2384
=> DASH-2384 [Frontend] Multiple company - refreshing pages issue

src/appsco-app.html, src/appsco-manage-account-page.html, src/directory/appsco-manage-account-components-page.html
https://webcomputing.jira.com/browse/DASH-2381
=> DASH-2381 [Frontend][Manage Account] Removing the last admin

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2335
=> DASH-2335 Directory page actions appearance fixed

src/appsco-app.html, src/appsco-directory-page.html
https://webcomputing.jira.com/browse/DASH-2335
=> DASH-2335 Directory page actions appearance when there is no subscription

src/application/appsco-home-page-actions.html, src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2264
=> DASH-2264 [Frontend]Home] Filtering applications

src/appsco-app.html, src/appsco-audit-log-page.html, src/auditlog/appsco-audit-log.html, src/auditlog/data/locales.json
https://webcomputing.jira.com/browse/DASH-2246
=> DASH-2246 [Frontend][Audit Log] Implement new log event type

src/appsco-statistics-page.html
https://webcomputing.jira.com/browse/DASH-2376
=> DASH-2376 Sharing an app to a non-company free user

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2380
=> DASH-2380 [Frontend][Domains] Unable to verify domain message

src/directory/appsco-directory-role-application.html, src/directory/appsco-directory-role-applications-page.html, src/directory/appsco-directory-role-applications.html, src/directory/appsco-manage-account-components-page.html
https://webcomputing.jira.com/browse/DASH-2331
=> DASH-2331 [Frontend][Manage Account] Role edit information text

src/applications/appsco-application-assignees-page.html, src/applications/appsco-manage-application-components-page.html, src/appsco-app.html, src/appsco-manage-application-page.html
https://webcomputing.jira.com/browse/DASH-2372
=> DASH-2372 [Frontend][Applications] - Assignees not reflecting org unit changes

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2372
=> DASH-2372 Reload assignees after application is added to orgunit

src/components/application/appsco-application-details.html
https://webcomputing.jira.com/browse/DASH-2433
=> DASH-2433 [Frontend][Audit Log] Remove copy from note

src/directory/appsco-directory-actions.html
https://webcomputing.jira.com/browse/DASH-2452
=> DASH-2452 [Frontend][Directory]Add user and Import user buttons should not disappear

src/components/account/appsco-accounts.html, src/components/label/appsco-company-label-item.html, src/components/label/appsco-company-label-role-item.html, src/components/label/appsco-resource-add-labels.html, src/components/label/appsco-resource-remove-labels.html
https://webcomputing.jira.com/browse/DASH-2305
=> DASH-2305 [Frontend][Labels] Fix when roles are selected

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2461
=> DASH-2461 [Company Home]Detach from label application remove

src/components/application/appsco-application-settings.html
https://webcomputing.jira.com/browse/DASH-2442
=> DASH-2442 Error when exiting settings page on personal creditcard item

src/appsco-company-home-page.html, src/appsco-home-page.html
https://webcomputing.jira.com/browse/DASH-2444
=> DASH-2444 [Frontend]Login info should only open Info section when clicked

src/appsco-app.html, src/components/header/appsco-header.html
https://webcomputing.jira.com/browse/DASH-2479
=> DASH-2479 Put back old vault links

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2467
=> DASH-2467 [Company Home] Delete label application remove

src/appsco-audit-log-page.html
https://webcomputing.jira.com/browse/DASH-2315
=> DASH-2315 [Frontend][Audit log]Preselect event type

src/appsco-trybusiness-page.html
https://webcomputing.jira.com/browse/DASH-2368
=> DASH-2368 [Frontend][Try Business] Provisioning image broken

src/components/orgunit/appsco-orgunit-item.html
https://webcomputing.jira.com/browse/DASH-2468
=> DASH-2468 [Directory] Org units long names

polymer.json, src/appsco-app.html, src/appsco-contacts-page.html
https://webcomputing.jira.com/browse/DASH-2405
=> DASH-2405 [Frontend][Contacts]Create Contacts page

src/application/appsco-application-subscribers-page.html, src/applications/appsco-application-assignees-page.html, src/appsco-account-page.html, src/appsco-app.html, src/appsco-application-page.html, src/appsco-applications-page.html, src/appsco-directory-page.html, src/appsco-home-page.html, src/appsco-manage-account-page.html, src/appsco-manage-application-page.html, src/auditlog/appsco-audit-log.html, src/components/account/appsco-account-details.html, src/components/account/appsco-account-image.html, src/components/account/appsco-account-item.html, src/components/account/appsco-invitation-item.html, src/components/application/appsco-account-card.html, src/components/application/appsco-application-subscriber.html, src/components/application/appsco-application-subscribers.html, src/components/application/company/appsco-application-assignee.html, src/components/application/company/appsco-application-assignees.html, src/components/header/appsco-account-chat.html, src/components/header/appsco-account-info-account.html, src/components/header/appsco-account-info.html, src/components/label/appsco-company-label-role-item.html, src/provisioning/appsco-integration-account.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2470
=> DASH-2470 [Frontend]Old account can have last or first name null

polymer.json, src/appsco-app.html, src/appsco-manage-contact-page.html, src/components/contact/appsco-manage-contact-page-actions.html
https://webcomputing.jira.com/browse/DASH-2409
=> DASH-2409 [Frontend][Manage contact]Create manage contact page

src/appsco-app.html, src/company/appsco-company-add-domain.html, src/components/components/appsco-api-errors.html, src/components/components/data/appsco-api-errors.json
https://webcomputing.jira.com/browse/DASH-2481
=> DASH-2481 [Frontend] Translate error messages component

src/components/application/appsco-application-actions.html, src/components/application/appsco-application-add-search.html, src/components/application/company/appsco-company-application-add-search.html
https://webcomputing.jira.com/browse/DASH-2459
=> DASH-2459 [Frontend][Resources]Add custom application

src/appsco-app.html, src/appsco-contacts-page.html, src/appsco-manage-contact-page.html, src/components/account/appsco-contact-item.html
https://webcomputing.jira.com/browse/DASH-2417
=> DASH-2417 [Frontend][Contacts]Implement edit on contact card

src/appsco-app.html, src/appsco-contacts-page.html
https://webcomputing.jira.com/browse/DASH-2407
=> DASH-2407 [Frontend][Contacts]Labels in resource section

src/appsco-app.html, src/appsco-contacts-page.html, src/appsco-directory-page.html, src/components/account/appsco-invitations.html, src/components/contact/appsco-contacts-actions.html, src/components/contact/appsco-contacts-page-actions.html
https://webcomputing.jira.com/browse/DASH-2415
=> DASH-2415 [Frontend][Contacts]Implement filter drop-down

src/components/application/appsco-application-add-settings.html
https://webcomputing.jira.com/browse/DASH-2459
=> DASH-2459 [Frontend][Resources]Add custom application - Animation fix

src/appsco-app.html, src/appsco-manage-contact-page.html
https://webcomputing.jira.com/browse/DASH-2417
=> DASH-2417 Set proper contact on edit action

src/appsco-app.html, src/appsco-contacts-page.html, src/components/account/appsco-contact-item.html, src/components/account/appsco-contacts.html, src/components/account/appsco-invitation-item.html, src/components/account/appsco-invitations.html, src/components/components/data/appsco-api-errors.json, src/components/contact/appsco-add-contact.html
https://webcomputing.jira.com/browse/DASH-2411
=> DASH-2411 [Frontend][Contacts]Implement Add contact

src/appsco-app.html, src/appsco-contacts-page.html, src/components/account/appsco-contacts.html, src/components/account/appsco-invitations.html
https://webcomputing.jira.com/browse/DASH-2416
=> DASH-2416 [Frontend][Contacts]Implement search filter

src/appsco-app.html, src/appsco-contacts-page.html, src/components/account/appsco-contact-item.html, src/components/account/appsco-contacts.html
https://webcomputing.jira.com/browse/DASH-2406
=> DASH-2406 [Frontend][Contacts]Implement contact page actions

src/appsco-app.html, src/components/application/appsco-application-share.html
https://webcomputing.jira.com/browse/DASH-2471
=> DASH-2471 [Frontend][Personal Home]Sharing to the same user twice

src/appsco-app.html, src/appsco-contacts-page.html, src/appsco-manage-contact-page.html, src/components/components/data/appsco-api-errors.json, src/components/contact/appsco-delete-contact.html
https://webcomputing.jira.com/browse/DASH-2422
=> DASH-2422 [Frontend][Manage contact]Implement remove contact on manage contact page

src/components/contact/appsco-add-contact.html
https://webcomputing.jira.com/browse/DASH-2411
=> DASH-2411 Send activation email input added

src/appsco-app.html, src/appsco-directory-page.html, src/components/components/data/appsco-api-errors.json, src/components/contact/appsco-convert-contact.html
https://webcomputing.jira.com/browse/DASH-2423
=> DASH-2423 [Frontend][Manage contacts]Convert contact to user

src/appsco-app.html, src/appsco-directory-page.html, src/components/account/appsco-invitations.html
https://webcomputing.jira.com/browse/DASH-2317
=> DASH-2317 [Frontend][Directory] Directory page invitation filtering

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2418
=> DASH-2418 [Frontend][Contacts]Implement resend action

src/components/application/appsco-application-log.html
https://webcomputing.jira.com/browse/DASH-2371
=> DASH-2371 [Frontend][Manage Application] Application log shows empty log for application removed from org unit

src/components/account/appsco-accounts.html, src/components/application/appsco-applications.html
https://webcomputing.jira.com/browse/DASH-2482
=> DASH-2482 [Applications] Double applications

src/appsco-app.html, src/appsco-contacts-page.html, src/components/account/appsco-contacts.html, src/components/contact/appsco-contacts-actions.html, src/components/contact/appsco-contacts-page-actions.html, src/components/contact/appsco-delete-contacts.html, src/components/label/appsco-resource-add-labels.html, src/components/label/appsco-resource-remove-labels.html
https://webcomputing.jira.com/browse/DASH-2414
=> DASH-2414 [Frontend][Contacts]Implement bulk action

src/appsco-app.html, src/appsco-contacts-page.html, src/components/account/appsco-contacts.html
https://webcomputing.jira.com/browse/DASH-2508
=> DASH-2508 [Contacts] Implement filter contacts by labels

src/appsco-company-home-page.html, src/appsco-home-page.html
https://webcomputing.jira.com/browse/DASH-2454
=> DASH-2454 [Backend]Company name should not be followed by company

src/appsco-app.html, src/appsco-contacts-page.html, src/components/contact/appsco-add-contact.html, src/directory/appsco-directory-add-account.html
https://webcomputing.jira.com/browse/DASH-2509
=> DASH-2509 [Frontend] Add account to company

src/appsco-manage-contact-page.html, src/components/contact/appsco-contact-application.html, src/components/contact/appsco-contact-applications-page.html, src/components/contact/appsco-contact-applications.html, src/components/contact/appsco-manage-contact-components-page.html, src/directory/appsco-directory-add-account.html
https://webcomputing.jira.com/browse/DASH-2514
=> DASH-2514 Polymer build does not work

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2484
=> DASH-2484 [Frontend][Applications] Application assignees updating

src/components/application/appsco-application-sharing-settings.html
https://webcomputing.jira.com/browse/DASH-2511
=> DASH-2511 Toggle on Sharing Settings not working

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2515
=> DASH-2515 [Contacts] Labels list not updating

src/appsco-app.html, src/company/appsco-company-add-domain.html, src/components/components/data/appsco-api-errors.json
https://webcomputing.jira.com/browse/DASH-2365
=> DASH-2365 [Frontend][Company settings] - Warning when adding managed domain

src/appsco-app.html, src/appsco-billing-page.html
https://webcomputing.jira.com/browse/DASH-2519
=> DASH-2519 [Billing] Subscription and credit card do not load

src/appsco-app.html, src/appsco-resources-page.html, src/components/application/appsco-application-share.html, src/components/application/company/appsco-company-application-share.html
https://webcomputing.jira.com/browse/DASH-2517
=> DASH-2517 [Frontend][Company][Resources] Sharing to the same user twice

src/components/account/appsco-contacts.html
https://webcomputing.jira.com/browse/DASH-2520
=> DASH-2520 [Frontend][Contacts] bulk remove removes only one account

src/appsco-app.html, src/components/account/company/appsco-account-remove.html, src/components/components/appsco-form-error.html, src/components/components/data/appsco-api-errors.json
https://webcomputing.jira.com/browse/DASH-2530
=> DASH-2530 [Directory] Removing last administrator from company not handled

src/components/account/company/appsco-account-remove.html, src/components/components/data/appsco-api-errors.json
https://webcomputing.jira.com/browse/DASH-2530
=> DASH-2530 AppsCo support link added

src/application/appsco-dialog-application-add.html, src/applications/appsco-dialog-application-company-add.html, src/components/application/appsco-application-add-settings.html, src/components/application/appsco-application-add.html, src/components/application/company/appsco-company-application-add-settings.html, src/components/application/company/appsco-company-application-add.html, src/components/application/company/appsco-company-sso-application-add.html
https://webcomputing.jira.com/browse/DASH-2535
=> DASH-2535 [Adding applications] Loader missing on some adding application forms

src/appsco-audit-log-page.html, src/auditlog/appsco-audit-log.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2538
=> DASH-2538 [Frontend][Audit Log] Implement load more

src/auditlog/appsco-audit-log.html
https://webcomputing.jira.com/browse/DASH-2538
=> DASH-2538 Filter log records by term fix

src/components/application/appsco-application-sharing-settings.html
https://webcomputing.jira.com/browse/DASH-2546
=> DASH-2546 Add support for saml_dropbox and saml_office_365 auth type

src/appsco-app.html, src/components/application/company/appsco-company-application-share.html
https://webcomputing.jira.com/browse/DASH-2040
=> DASH-2040 [Frontend] Sharing company apps logic

src/applications/appsco-manage-application-components-page.html, src/appsco-app.html, src/appsco-manage-resource-page.html, src/components/application/appsco-application-details-idp.html
https://webcomputing.jira.com/browse/DASH-2551
=> DASH-2551 [Front][Manage Resource] Create new card Appsco IdP information

src/applications/appsco-manage-application-components-page.html, src/appsco-app.html, src/appsco-manage-resource-page.html
https://webcomputing.jira.com/browse/DASH-2550
=> DASH-2550 [Front][Manage Resource] Remove Sharing settings card

src/appsco-app.html, src/appsco-contacts-page.html, src/components/account/appsco-contacts.html, src/components/contact/appsco-contacts-page-actions.html
https://webcomputing.jira.com/browse/DASH-2518
=> DASH-2518 [Frontend][Contacts]Add show/hide info and resource actions to actions header

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2488
=> DASH-2488 [Company Home] 403 messages on shared company

src/company/appsco-company-add-domain.html
https://webcomputing.jira.com/browse/DASH-2521
=> DASH-2521 [Fontend] Add managed domain link to support

src/appsco-provisioning-settings-page.html
https://webcomputing.jira.com/browse/DASH-2578
=> DASH-2578 [Frontend][Provisioning]Remove settings from resource section

src/appsco-statistics-page.html
https://webcomputing.jira.com/browse/DASH-2308
=> DASH-2308 [Frontend] Statistics issue

src/applications/appsco-manage-application-components-page.html
https://webcomputing.jira.com/browse/DASH-2599
=> DASH-2599 [Frontend]AppsCo IdP information card should be available only for SSO applications

src/appsco-statistics-page.html
https://webcomputing.jira.com/browse/DASH-2603
=> DASH-2603 [Front] Optimize appsco-statistics-page

src/components/application/appsco-application-log.html
https://webcomputing.jira.com/browse/DASH-2506
=> DASH-2506 [Applications] No log for adding apps into org units

src/components/application/appsco-application-settings-card.html
https://webcomputing.jira.com/browse/DASH-2612
=> DASH-2612 [Frontend][Manage resource] Text on settings card should break

src/appsco-provisioning-page.html
https://webcomputing.jira.com/browse/DASH-2609
=> DASH-2609 [Provisioning] Get integrations API is not called in proper manner

src/appsco-home-page.html
https://webcomputing.jira.com/browse/DASH-2608
=> DASH-2608 [Front][Personal Home] Link has no share in info

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2611
=> DASH-2611 [Front] Fix menu to respond correctly to environment

src/components/application/company/appsco-company-resource-settings.html
https://webcomputing.jira.com/browse/DASH-2549
https://webcomputing.jira.com/browse/DASH-2613
=> DASH-2549 Load resource settings fixed

src/components/application/company/appsco-company-resource-settings.html, src/components/components/data/appsco-api-errors.json
https://webcomputing.jira.com/browse/DASH-2545
=> DASH-2545 [Frontend] Remove individual/global toggle for SSO SAML resources

src/applications/appsco-manage-application-components-page.html, src/appsco-app.html, src/components/application/appsco-application-details-idp.html
https://webcomputing.jira.com/browse/DASH-2621
=> DASH-2621 [Manage Resource] IdP information improvements

src/provisioning/appsco-integration-page.html
https://webcomputing.jira.com/browse/DASH-2121
=> DASH-2121 [Backend]Directory Integration Provisioning Setup with Office365

src/components/application/appsco-application-details-idp.html
https://webcomputing.jira.com/browse/DASH-2630
=> DASH-2630 [Frontend][Manage resource] Add certificate fingerprint to IdP Information card

src/appsco-provisioning-page.html
https://webcomputing.jira.com/browse/DASH-2576
=> DASH-2576 [Frontend][Provisioning]Add Azure to available integrations

src/appsco-company-home-page.html, src/appsco-home-page.html
https://webcomputing.jira.com/browse/DASH-2638
=> DASH-2638 Fix saml_dropbox and saml_office_365 icons

src/appsco-app.html, src/components/application/appsco-application-actions.html, src/components/application/appsco-application-form-behavior.html, src/components/application/appsco-application-form-cc.html, src/components/application/appsco-application-form-item.html, src/components/application/appsco-applications.html, src/components/application/appsco-import-resources.html, src/components/components/appsco-import-resource.html
https://webcomputing.jira.com/browse/DASH-2607
=> DASH-2607 [Frontend][Company Resources]Add import from LastPass

src/applications/appsco-manage-application-components-page.html
https://webcomputing.jira.com/browse/DASH-2636
=> DASH-2636 [Frontend][Manage Resource] Remove security card on all resources except

src/components/application/appsco-application-actions.html
https://webcomputing.jira.com/browse/DASH-2663
=> DASH-2663 Import from LastPass should not be available on Personal

src/appsco-app.html, src/appsco-company-page.html
https://webcomputing.jira.com/browse/DASH-2664
=> DASH-2664 [Company page] Page progress bar does not show

src/components/components/appsco-form-error.html, src/components/components/data/appsco-api-errors.json
https://webcomputing.jira.com/browse/DASH-2665
=> DASH-2665 [Frontend][Directory] Adding existing user

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2662
=> DASH-2662 [Company] Attach label modal hanging

src/components/application/company/appsco-company-application-sso-list.html
https://webcomputing.jira.com/browse/DASH-2541
=> DASH-2541 [Frontend][Company] Add SSO application modal

src/appsco-manage-account-page.html
https://webcomputing.jira.com/browse/DASH-2660
=> DASH-2660 [Company][Directory] Unable to edit managed user

src/appsco-app.html, src/appsco-trybusiness-page.html, src/company/appsco-company-settings.html, src/components/components/data/appsco-api-errors.json
https://webcomputing.jira.com/browse/DASH-2585
https://webcomputing.jira.com/browse/DASH-2587
=> DASH-2585 [Frontend][Personal]Implement can create company

src/appsco-app.html, src/components/components/appsco-api.html
https://webcomputing.jira.com/browse/DASH-2594
=> DASH-2594 [Frontend]List all companies where account is contact

src/appsco-app.html, src/appsco-contacts-page.html, src/appsco-directory-page.html, src/components/contact/appsco-contacts-actions.html, src/components/contact/appsco-contacts-page-actions.html, src/directory/appsco-directory-actions.html, src/directory/appsco-directory-page-actions.html
https://webcomputing.jira.com/browse/DASH-2617
=> DASH-2617 [Frontend]Remove bulk action - remove labels

polymer.json, src/appsco-app.html, src/appsco-company-account-page.html, src/company-account/appsco-company-account-page-actions.html, src/components/account/appsco-account-transfer-token.html, src/components/header/appsco-product.html
https://webcomputing.jira.com/browse/DASH-2614
=> DASH-2614 [Frontend][My Account] Expand My account with company branding

src/appsco-app.html, src/components/application/appsco-application-actions.html, src/components/label/appsco-resource-add-labels.html
https://webcomputing.jira.com/browse/DASH-2618
=> DASH-2618 [Frontend][Resources] Share to group

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2688
=> DASH-2688 [Frontend] Error in appsco-app.html

src/appsco-app.html, src/appsco-provisioning-settings-page.html, src/provisioning/appsco-provisioning-settings-page-actions.html
https://webcomputing.jira.com/browse/DASH-2686
=> DASH-2686 O365 Directory sync is only showing default onmicrosoft.com email

polymer.json, src/appsco-app.html, src/appsco-contact-home-page.html, src/company/appsco-contact-home-page-actions.html
https://webcomputing.jira.com/browse/DASH-2595
=> DASH-2595 [Frontend] Create Contact Home page

src/appsco-app.html, src/appsco-company-page.html, src/appsco-contacts-page.html, src/appsco-directory-page.html, src/company/appsco-company-components-page.html, src/company/appsco-company-page-actions.html, src/components/account/appsco-account-item.html, src/components/account/appsco-accounts.html, src/components/account/appsco-contacts.html, src/components/application/appsco-application-item.html, src/components/contact/appsco-contacts-actions.html, src/components/group/appsco-company-add-group.html, src/components/group/appsco-company-group-info-page.html, src/components/group/appsco-company-group-item.html, src/components/group/appsco-company-group-role-item.html, src/components/group/appsco-company-group-roles.html, src/components/group/appsco-company-groups-page.html, src/components/group/appsco-company-groups.html, src/components/group/appsco-company-manage-groups-page.html, src/components/group/appsco-company-remove-group.html, src/components/group/appsco-group-card.html, src/components/group/appsco-resource-add-groups.html, src/components/group/appsco-resource-remove-groups.html, src/directory/appsco-directory-actions.html
https://webcomputing.jira.com/browse/DASH-2624
=> DASH-2624 [Frontend] Rename Labels to Groups

src/appsco-company-page.html, src/company/appsco-company-components-page.html
https://webcomputing.jira.com/browse/DASH-2629
=> DASH-2629 [Frontend] Remove labels card from Company settings

src/components/application/appsco-application-actions.html, src/components/contact/appsco-contacts-actions.html, src/directory/appsco-directory-actions.html
https://webcomputing.jira.com/browse/DASH-2616
=> DASH-2616 [Frontend]Replace Labels icon with Groups icon

src/appsco-app.html, src/appsco-manage-account-page.html, src/components/account/company/appsco-account-groups-item.html, src/components/account/company/appsco-account-groups.html, src/components/account/company/appsco-account-remove-group.html, src/directory/appsco-account-groups-page.html, src/directory/appsco-manage-account-components-page.html
https://webcomputing.jira.com/browse/DASH-2620
=> DASH-2620 [Frontend][Manage account]Add Groups card to manage account

src/appsco-app.html, src/appsco-manage-contact-page.html, src/components/contact/appsco-contact-group-item.html, src/components/contact/appsco-contact-groups-page.html, src/components/contact/appsco-contact-groups.html, src/components/contact/appsco-contact-remove-group.html, src/components/contact/appsco-manage-contact-components-page.html
https://webcomputing.jira.com/browse/DASH-2623
=> DASH-2623 [Frontend][Contacts] Add Groups card to manage contact

src/components/components/appsco-country-list.html
https://webcomputing.jira.com/browse/DASH-2669
=> DASH-2669 [Resource] Passport country selector

polymer.json, src/appsco-app.html, src/appsco-manage-group-page.html, src/components/group/appsco-manage-group-actions.html, src/components/group/appsco-manage-group-page-actions.html
https://webcomputing.jira.com/browse/DASH-2641
=> DASH-2641 [Fontend][Manage Group] Create Manage Group page

src/components/group/appsco-company-group-contacts.html, src/components/group/appsco-company-group-resources.html, src/components/group/appsco-company-group-role-item.html, src/components/group/appsco-company-group-roles.html
https://webcomputing.jira.com/browse/DASH-2625
=> DASH-2625 [Frontend][Groups] Add Groups to left navigation and create groups page

src/appsco-app.html, src/appsco-company-page.html, src/company/appsco-company-components-page.html, src/company/appsco-company-idp-domain-item.html, src/company/appsco-company-idp-domains-page.html, src/company/appsco-company-idp-domains.html, src/company/appsco-company-idp-settings-page.html, src/company/appsco-company-idp-settings.html, src/company/appsco-company-manage-idp-settings-page.html, src/company/appsco-deactivate-idp-settings.html, src/components/contact/appsco-contact-groups-page.html, src/directory/appsco-account-groups-page.html
https://webcomputing.jira.com/browse/DASH-2651
=> DASH-2651 [Frontend][Company Settings] Create card for IdP settings

src/appsco-app.html, src/components/group/appsco-company-groups.html
https://webcomputing.jira.com/browse/DASH-2627
=> DASH-2627 [Frontend][Groups] Implement search groups

src/appsco-app.html, src/appsco-groups-page.html, src/company/appsco-company-idp-settings.html, src/components/group/appsco-company-group-item.html, src/components/group/appsco-company-remove-group.html
https://webcomputing.jira.com/browse/DASH-2643
=> DASH-2643 [Frontend][Manage Group] Implement Remove action

src/appsco-app.html, src/appsco-groups-page.html, src/components/components/data/appsco-api-errors.json, src/components/group/appsco-company-add-group.html
https://webcomputing.jira.com/browse/DASH-2626
=> DASH-2626 [Frontend][Groups] Implement Create group

src/appsco-app.html, src/appsco-contacts-page.html, src/appsco-directory-page.html, src/appsco-resources-page.html
https://webcomputing.jira.com/browse/DASH-2615
=> DASH-2615 [Frontend][Resources] - refresh group list after remove group

src/appsco-app.html, src/appsco-groups-page.html, src/appsco-manage-group-page.html, src/components/group/appsco-company-group-contact-item.html, src/components/group/appsco-company-group-contacts.html, src/components/group/appsco-company-group-item.html, src/components/group/appsco-company-groups.html, src/components/group/appsco-group-contacts-page.html, src/components/group/appsco-manage-group-components-page.html, src/components/group/appsco-resource-remove-from-group.html
https://webcomputing.jira.com/browse/DASH-2645
=> DASH-2645 [Frontend][Manage Group] Create and implement Contacts card on manage group

src/appsco-app.html, src/appsco-manage-group-page.html, src/components/application/appsco-application-card.html, src/components/group/appsco-group-add-resource.html, src/components/group/appsco-manage-group-actions.html
https://webcomputing.jira.com/browse/DASH-2655
=> DASH-2655 [Frontend][Manage Group] Implement Add to group action

src/appsco-app.html, src/appsco-groups-page.html, src/appsco-manage-group-page.html, src/components/group/appsco-company-group-resource-item.html, src/components/group/appsco-company-group-resources.html, src/components/group/appsco-group-resources-page.html, src/components/group/appsco-manage-group-components-page.html, src/components/group/appsco-resource-remove-from-group.html
https://webcomputing.jira.com/browse/DASH-2646
=> DASH-2646 [Frontend][Manage Group] Create Shared Resources card on manage group page

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2715
=> DASH-2715 Change Directory icon in company menu

src/components/application/appsco-application-details-idp.html
https://webcomputing.jira.com/browse/DASH-2684
=> DASH-2684 [Frontend][Resources] SAML certificate and IdP Metadata download

src/appsco-app.html, src/appsco-contacts-page.html, src/appsco-groups-page.html, src/components/group/appsco-company-group-contact-item.html, src/components/group/appsco-company-group-contacts.html, src/components/group/appsco-company-group-image.html, src/components/group/appsco-company-group-item.html, src/components/group/appsco-company-group-roles.html, src/components/group/appsco-company-groups.html, src/components/group/appsco-group-actions.html, src/components/group/appsco-groups-page-actions.html, src/components/group/appsco-manage-group-components-page.html
https://webcomputing.jira.com/browse/DASH-2714
=> DASH-2714 [Groups page] Fix style and behaviour

src/appsco-groups-page.html, src/components/group/appsco-company-group-contacts.html, src/components/group/appsco-company-group-resources.html, src/components/group/appsco-company-group-roles.html, src/components/group/appsco-manage-group-actions.html
https://webcomputing.jira.com/browse/DASH-2714
=> DASH-2714 Groups page: style in info section improved

src/company/appsco-company-idp-settings.html, src/company/appsco-company-manage-idp-settings-page.html
https://webcomputing.jira.com/browse/DASH-2722
=> DASH-2722 [IdP Settings] Parse XML metadata for GSuite

src/company/appsco-company-idp-settings.html
https://webcomputing.jira.com/browse/DASH-2722
=> DASH-2722 XML parse fix

src/appsco-app.html, src/appsco-company-page.html
https://webcomputing.jira.com/browse/DASH-2677
=> DASH-2677 [Frontend][Company Settings] Changing the company name

src/components/application/company/appsco-company-resource-settings.html
https://webcomputing.jira.com/browse/DASH-2708
=> DASH-2708 [Frontend][Manage Resource] Unable to close settings for link resource

src/applications/appsco-application-assignees-page.html, src/applications/appsco-manage-application-components-page.html, src/appsco-app.html, src/appsco-company-page.html, src/appsco-manage-resource-page.html, src/appsco-resources-page.html, src/components/application/company/appsco-application-assignee.html, src/components/application/company/appsco-application-assignees.html, src/components/application/company/appsco-company-application-remove.html, src/components/application/demo/company/appsco-application-assignees.html, src/components/group/appsco-company-group-item.html
https://webcomputing.jira.com/browse/DASH-2472
=> DASH-2472 [Frontend] refactor appsco-application-assignees.html

src/components/application/company/appsco-application-assignees.html
https://webcomputing.jira.com/browse/DASH-2472
=> DASH-2472 Removing proper assignee from list

src/components/application/appsco-application-details.html
https://webcomputing.jira.com/browse/DASH-2709
=> DASH-2709 [Frontend][Company Dashboard] Link resource not showing the link in info section

src/provisioning/appsco-integration-page.html
https://webcomputing.jira.com/browse/DASH-2721
=> DASH-2721 [Provisioning] Syncing users issue

src/account/appsco-account-2fa-manage.html, src/account/appsco-account-disable-2fa.html, src/appsco-account-page.html, src/appsco-app.html, src/appsco-company-account-page.html
https://webcomputing.jira.com/browse/DASH-2602
=> DASH-2602 [Frontend][Account] 2fa disable confirm

src/appsco-statistics-page.html
https://webcomputing.jira.com/browse/DASH-2610
=> DASH-2610 [Frontend][Statistics]Default graph for Application usage

src/components/account/appsco-accounts.html, src/components/account/appsco-contacts.html, src/components/application/appsco-applications.html
https://webcomputing.jira.com/browse/DASH-2718
=> DASH-2718 [Frontend] Duplicated entries in list when filtering resources by group

src/company/appsco-company-components-page.html, src/company/appsco-company-page-actions.html
https://webcomputing.jira.com/browse/DASH-2680
=> DASH-2680 [Company Settings] New company creation errors

src/components/components/data/appsco-api-errors.json
https://webcomputing.jira.com/browse/DASH-2437
=> DASH-2437 [Frontend][Manage Account] Add error message when trying to remove the last admin

src/appsco-billing-page.html
https://webcomputing.jira.com/browse/DASH-2760
=> DASH-2760 [Frontend][Billing] Missing spaces in upcoming invoice text

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2762
=> DASH-2762 [Frontend][Company Settings] Unable to verify domain toast message

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2741
=> DASH-2741 [Resource] Assignee list Score - claims relation

src/appsco-app.html, src/appsco-company-page.html, src/company/appsco-company-idp-domains-page.html, src/company/appsco-company-idp-domains.html, src/company/appsco-company-manage-idp-settings-page.html
https://webcomputing.jira.com/browse/DASH-2727
=> DASH-2727 [Frondend][IdP Settings] Add message for when there are no verified domains

src/components/application/company/appsco-application-assignee.html
https://webcomputing.jira.com/browse/DASH-2742
=> DASH-2742 [Manage Resource] Assignee list Security Score for ex-Vault items and SAML resources

src/appsco-manage-resource-page.html
https://webcomputing.jira.com/browse/DASH-2499
=> DASH-2499 App-spesific link to support article on manage resource page

src/components/account/appsco-contacts.html
https://webcomputing.jira.com/browse/DASH-2703
=> DASH-2703 No contacts attached to group message

src/components/components/data/appsco-api-errors.json
https://webcomputing.jira.com/browse/DASH-2757
=> DASH-2757 [Frontend][Contacts] Error code should be displayed as text

src/components/application/appsco-application-form-softwarelicence.html
https://webcomputing.jira.com/browse/DASH-2707
=> DASH-2707 Software licence - reorder fields

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2671
=> DASH-2671 Company dropdown not sorted alphabetically

src/appsco-app.html, src/components/account/appsco-contact-item.html
https://webcomputing.jira.com/browse/DASH-2704
=> DASH-2704 [Contacts] Groups not visible on contact cards

src/appsco-app.html, src/appsco-contacts-page.html, src/appsco-customers-page.html, src/appsco-directory-page.html, src/appsco-resources-page.html, src/components/customer/appsco-customer-details.html, src/components/customer/appsco-customers-page-actions.html, src/components/page/appsco-page-global.html
https://webcomputing.jira.com/browse/DASH-2747
=> DASH-2747 [Frontend][Customers] Implement info section

src/appsco-app.html, src/appsco-audit-log-page.html, src/appsco-contacts-page.html, src/appsco-customers-page.html, src/appsco-directory-page.html, src/appsco-groups-page.html, src/appsco-resources-page.html, src/auditlog/appsco-audit-log.html, src/auditlog/data/locales.json, src/components/application/appsco-application-log.html, src/components/application/company/appsco-company-resources.html, src/components/components/appsco-list-behavior.html, src/components/components/appsco-list-item-behavior.html, src/components/components/appsco-list-item-styles.html, src/components/customer/appsco-customer-details.html, src/components/customer/appsco-customer-item.html, src/components/customer/appsco-customers-page-actions.html, src/components/customer/appsco-customers.html, src/components/group/appsco-company-group-item.html, src/components/group/appsco-company-groups.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2746
=> DASH-2746 [Frontend][Customers] Create list of customers

src/appsco-app.html, src/appsco-customers-page.html, src/components/contact/appsco-contacts-actions.html, src/components/contact/appsco-contacts-page-actions.html, src/components/customer/appsco-customers-actions.html, src/components/customer/appsco-customers-page-actions.html
https://webcomputing.jira.com/browse/DASH-2748
=> DASH-2748 [Frontend][Customers] Implement search filter

src/appsco-app.html, src/appsco-customers-page.html, src/components/components/appsco-list-item-behavior.html, src/components/components/appsco-search.html, src/components/customer/appsco-add-customer.html, src/components/customer/appsco-customers-actions.html, src/components/header/appsco-product.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2752
=> DASH-2752 [Frontend][Customers] Implement Add customer action

src/appsco-app.html, src/appsco-customers-page.html, src/components/components/appsco-import-resource.html, src/components/components/appsco-list-behavior.html, src/components/customer/appsco-import-customers.html
https://webcomputing.jira.com/browse/DASH-2750
=> DASH-2750 [Frontend][Customers] Implement import customers action

src/appsco-app.html, src/appsco-directory-page.html, src/components/account/appsco-accounts.html, src/directory/appsco-directory-actions.html, src/directory/appsco-directory-page-actions.html
https://webcomputing.jira.com/browse/DASH-2678
=> DASH-2678 [Frontend][Directory] Implement filter drop-down in Directory

polymer.json, src/appsco-app.html, src/appsco-customers-page.html, src/appsco-manage-customer-page.html, src/components/customer/appsco-manage-customer-page-actions.html
https://webcomputing.jira.com/browse/DASH-2753
=> DASH-2753 [Frontend][Customers] Create Manage customer page

src/appsco-app.html, src/appsco-customers-page.html, src/components/customer/appsco-customers-actions.html
https://webcomputing.jira.com/browse/DASH-2749
=> DASH-2749 [Frontend][Customers] Implement export to .csv

src/appsco-app.html, src/components/customer/appsco-add-customer.html
https://webcomputing.jira.com/browse/DASH-2752
=> DASH-2752 Info if customer exists

src/appsco-app.html, src/appsco-directory-page.html, src/components/account/appsco-accounts.html, src/components/account/appsco-invitations.html, src/components/components/appsco-list-behavior.html, src/directory/appsco-directory-actions.html, src/directory/appsco-directory-page-actions.html
https://webcomputing.jira.com/browse/DASH-2682
=> DASH-2682 [Frontend][Directory] Search filter should search based on the drop down filter

src/appsco-app.html, src/appsco-customers-page.html, src/components/customer/appsco-add-partner-admin-to-customers.html, src/components/customer/appsco-customers-actions.html, src/components/customer/appsco-customers-page-actions.html, src/components/customer/appsco-customers.html, src/components/customer/appsco-remove-customers.html
https://webcomputing.jira.com/browse/DASH-2756
=> DASH-2756 [Frontend][Customers] Implement bulk actions

src/components/application/company/appsco-application-assignee-claims.html
https://webcomputing.jira.com/browse/DASH-2767
=> DASH-2767 [Resource] Save claims on FF

src/components/application/appsco-application-actions.html
https://webcomputing.jira.com/browse/DASH-2752
=> DASH-2752 Info text showing fix

src/components/customer/appsco-add-partner-admin-to-customers.html
https://webcomputing.jira.com/browse/DASH-2758
=> DASH-2758 [Frontend][Manage customer] Implement partner admins card and implement actions

src/components/application/appsco-application-actions.html
https://webcomputing.jira.com/browse/DASH-2769
=> DASH-2769 [Frontend] Add resource button does not work on small screens

src/directory/appsco-manage-account-components-page.html
https://webcomputing.jira.com/browse/DASH-2794
=> DASH-2794 Remove Company roles card from Partner admin in customer directory

src/appsco-app.html, src/components/header/appsco-header.html, src/components/header/appsco-product.html
https://webcomputing.jira.com/browse/DASH-2787
=> DASH-2787 [Frontend][Customers] Removing customers update

src/appsco-customers-page.html, src/components/customer/appsco-add-customer.html, src/components/customer/appsco-customer-details.html
https://webcomputing.jira.com/browse/DASH-2747
=> DASH-2747 Customer log API added

src/appsco-app.html, src/components/customer/appsco-add-customer.html
https://webcomputing.jira.com/browse/DASH-2752
=> DASH-2752 Info regarding existing customer

src/appsco-app.html, src/appsco-customers-page.html, src/components/components/appsco-list-behavior.html
https://webcomputing.jira.com/browse/DASH-2799
=> DASH-2799 [Frontend][Customers] Hide page if company is not partner

src/appsco-manage-customer-page.html
https://webcomputing.jira.com/browse/DASH-2796
=> DASH-2796 [Frontend][Customers] Customer uuid

src/components/customer/appsco-company-partner-admin-item.html
https://webcomputing.jira.com/browse/DASH-2795
=> DASH-2795 [Frontend][Manage Customer] Remove security score from partner admins cards

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2786
=> DASH-2786 [Frontend][Customers] Customers listing

src/appsco-app.html, src/appsco-manage-resource-page.html
https://webcomputing.jira.com/browse/DASH-2826
=> DASH-2826 Share resource form triggered from information section hangs

src/appsco-app.html, src/appsco-customers-page.html, src/appsco-page-styles.html, src/appsco-reports-page.html, src/components/report/appsco-reports-page-actions.html
https://webcomputing.jira.com/browse/DASH-2832
=> DASH-2832 [Frontend][Reports] Add Reports to menu and create reports page

src/components/resource/appsco-resource-auth-type.html, src/components/resource/data/appsco-auth-type-translations.json
https://webcomputing.jira.com/browse/DASH-2838
=> DASH-2838 [Frontend] Display resource auth types on front end

src/components/application/appsco-application-details-cc.html, src/components/application/appsco-application-details-passport.html, src/components/application/appsco-application-details-softwarelicence.html
https://webcomputing.jira.com/browse/DASH-2668
=> DASH-2668 [Resource] Vault items sharing issues

src/appsco-access-report-page.html, src/appsco-app.html, src/components/components/appsco-list-behavior.html, src/components/components/appsco-list-item-styles.html, src/components/report/appsco-access-report-account-item.html, src/components/report/appsco-access-report-account-resource-item.html, src/components/report/appsco-access-report-accounts.html
https://webcomputing.jira.com/browse/DASH-2836
=> DASH-2836 [Frontend][Access report] Create report list

src/components/application/appsco-application-details-securenote.html
https://webcomputing.jira.com/browse/DASH-2845
=> DASH-2845 Secure note suggestion

src/appsco-access-report-page.html, src/appsco-app.html, src/appsco-page-styles.html, src/appsco-reports-page.html, src/components/report/appsco-access-report-details.html, src/components/report/appsco-access-report-item.html, src/components/report/appsco-access-report-page-actions.html
https://webcomputing.jira.com/browse/DASH-2833
=> DASH-2833 [Frontend][Reports] Create Access report card on Reports and implement actions

src/appsco-access-report-page.html, src/appsco-app.html, src/appsco-audit-log-page.html, src/components/components/appsco-list-behavior.html, src/components/report/appsco-access-report-accounts.html, src/components/report/appsco-access-report-page-filters.html
https://webcomputing.jira.com/browse/DASH-2835
=> DASH-2835 [Frontend][Access report] Implement filters on Access report page

src/applications/appsco-manage-application-components-page.html, src/components/application/appsco-application-autologin.html
https://webcomputing.jira.com/browse/DASH-2851
=> DASH-2851 [Company][Resource] Autologin card

src/appsco-access-report-page.html, src/appsco-app.html, src/appsco-customers-page.html, src/appsco-reports-page.html, src/components/report/appsco-access-report-actions.html, src/components/report/appsco-access-report-page-actions.html, src/components/report/appsco-access-report-page-filters.html
https://webcomputing.jira.com/browse/DASH-2837
=> DASH-2837 [Frontend][Access report] Implement Export action

src/appsco-audit-log-page.html, src/auditlog/appsco-audit-log.html, src/auditlog/data/locales.json
https://webcomputing.jira.com/browse/DASH-2847
=> DASH-2847 [Frontend][Audit log] Implement new event types

src/components/account/appsco-account-log-item.html
https://webcomputing.jira.com/browse/DASH-2850
=> DASH-2850 [Frontend][Manage Account] Add default icon to Activity log

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2837
=> DASH-2837 Export api url fixed

src/appsco-access-report-page.html
https://webcomputing.jira.com/browse/DASH-2858
=> DASH-2858 [Front-end][Access Report] Switch between users and contacts

src/appsco-access-report-page.html
https://webcomputing.jira.com/browse/DASH-2858
=> DASH-2858 Commented code removed

src/applications/appsco-dialog-application-company-add.html, src/appsco-app.html, src/components/application/appsco-application-actions.html, src/components/application/appsco-application-form-passport.html, src/components/application/company/appsco-company-application-add-settings.html, src/components/application/company/appsco-company-application-add.html, src/components/application/company/appsco-company-sso-application-add.html
https://webcomputing.jira.com/browse/DASH-2441
=> DASH-2441 [Frontend][Resources] Resource configuration in initial dialog

src/appsco-customers-page.html
https://webcomputing.jira.com/browse/DASH-2853
=> DASH-2853 [Frontend][Customers] Customers icon on info section

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2871
=> DASH-2871 [Front end][Resources] When link is aded to resources, page is not refreshing

src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2861
=> DASH-2861 [Front end][Resources] Resource and password modal issue

src/account/appsco-account-page-actions.html, src/appsco-app.html, src/appsco-company-account-page.html, src/appsco-directory-page.html, src/components/account/appsco-account-actions.html, src/components/account/appsco-accounts.html, src/directory/appsco-manage-account-page-actions.html
https://webcomputing.jira.com/browse/DASH-2862
=> DASH-2862 [Front end][Directory] User name update

src/components/application/appsco-application-form-behavior.html
https://webcomputing.jira.com/browse/DASH-2870
=> DASH-2870 [Front end][Resources] Credit card field validation not refreshing

polymer.json
https://webcomputing.jira.com/browse/DASH-2874
=> DASH-2874 [Company][Resources] Credit card image broken

src/components/application/appsco-application-details-idp.html
https://webcomputing.jira.com/browse/APP-691
=> APP-691 Freshdesk | Added sha256 key fingerprint to SAML idp info

src/auditlog/appsco-audit-log.html
https://webcomputing.jira.com/browse/DASH-2856
=> DASH-2856 [Frontend][Audit log] Add new column to Audit log and display additional information

src/appsco-company-page.html, src/auditlog/appsco-audit-log.html, src/auditlog/data/locales.json, src/company/appsco-company-settings-page.html, src/company/appsco-company-settings.html
https://webcomputing.jira.com/browse/DASH-2879
=> DASH-2879 [Back end] Implement new event type Enforce two-factor authentication

src/appsco-company-page.html, src/company/appsco-company-settings-page.html, src/company/appsco-company-settings.html
https://webcomputing.jira.com/browse/DASH-2867
=> DASH-2867 [Front end][Company Settings] Add Enforce 2fa toggle

src/appsco-app.html, src/appsco-manage-account-page.html, src/components/company-role/appsco-role-reset-two-fa.html, src/directory/appsco-manage-account-components-page.html, src/directory/appsco-manage-account-twofa-page.html
https://webcomputing.jira.com/browse/DASH-2868
=> DASH-2868 [Front end][Account Settings] Implement manage 2fa

src/account/appsco-account-components-page.html, src/appsco-app.html, src/appsco-company-account-page.html
https://webcomputing.jira.com/browse/DASH-2869
=> DASH-2869 [Front end][My Account] Hide 2fa card for managed users when company has enforced 2fa policy on

src/components/application/company/appsco-company-application-add-settings.html
https://webcomputing.jira.com/browse/DASH-2889
=> DASH-2889 [Frontend][Resources] Add SSO Application dialog missing info text

src/applications/appsco-manage-application-components-page.html, src/appsco-company-page.html, src/appsco-contact-home-page.html, src/appsco-manage-customer-page.html, src/appsco-manage-group-page.html, src/appsco-manage-resource-page.html, src/auditlog/appsco-audit-log.html, src/components/account/appsco-account-log-item.html, src/components/account/appsco-account-log.html, src/components/components/appsco-list-item.html, src/components/contact/appsco-contact-group-item.html, src/components/group/appsco-company-group-item.html, src/components/group/appsco-company-group-resource-item.html, src/components/group/appsco-company-group-roles.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2897
=> DASH-2897 Fixed issue with long names (w/o spaces)

src/auditlog/appsco-audit-log.html, src/auditlog/data/locales.json, src/components/components/data/event-types.json
https://webcomputing.jira.com/browse/DASH-2881
=> DASH-2881 [Back end] Add new event type when report is exported

src/appsco-audit-log-page.html
https://webcomputing.jira.com/browse/DASH-2902
=> DASH-2902 [Audit log] Event type search filter matching only by one word

src/components/components/data/event-types.json
https://webcomputing.jira.com/browse/DASH-2879
=> DASH-2879 [Back end] Implement new event type Enforce two-factor authentication - fix

src/application/appsco-resource-image-settings.html, src/appsco-app.html, src/appsco-manage-resource-page.html
https://webcomputing.jira.com/browse/DASH-2884
=> DASH-2884 [Frontend][Manage Resource] Implement upload resource icon

src/appsco-app.html, src/appsco-manage-account-page.html, src/directory/appsco-manage-account-components-page.html
https://webcomputing.jira.com/browse/DASH-2868
=> DASH-2868 Manage 2fa action disabled if enforce 2fa policy is off

src/appsco-app.html, src/components/components/appsco-list-item-styles.html, src/components/resource/appsco-account-list-item.html, src/components/resource/appsco-share-resource.html
https://webcomputing.jira.com/browse/DASH-2876
=> DASH-2876 [Front end] Change share to user/contact dialog

src/components/application/appsco-application-form-saml.html
https://webcomputing.jira.com/browse/DASH-2883
=> DASH-2883 [Company][Resources] Saml resources fields text

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2876
=> DASH-2876 Old share component cleanup

src/appsco-manage-resource-page.html
https://webcomputing.jira.com/browse/DASH-2905
=> DASH-2905 Fixed the rendering of the support article link.

src/components/resource/appsco-share-resource.html
https://webcomputing.jira.com/browse/DASH-2876
=> DASH-2876 List all users always in share component

src/appsco-manage-contact-page.html, src/components/contact/appsco-manage-contact-components-page.html
https://webcomputing.jira.com/browse/DASH-2894
=> DASH-2894 [Front End][Contacts] Edit contact responsive issue

src/appsco-groups-page.html, src/components/group/appsco-company-groups.html
https://webcomputing.jira.com/browse/DASH-2906
=> DASH-2906 [Front End][Groups] Implement select on Groups page

src/appsco-customers-page.html, src/company/appsco-company-settings.html, src/components/header/appsco-product.html
https://webcomputing.jira.com/browse/DASH-2901
=> DASH-2901 [Company Settings] Company name limit the number of characters

src/appsco-app.html, src/appsco-groups-page.html, src/components/group/appsco-delete-groups.html, src/components/group/appsco-group-actions.html, src/components/group/appsco-groups-page-actions.html
https://webcomputing.jira.com/browse/DASH-2907
=> DASH-2907 [Front End][Groups] Add Remove bulk action and implement it

src/components/application/appsco-application-details-securenote.html
https://webcomputing.jira.com/browse/DASH-2915
=> DASH-2915 Modify secure note functionality

src/appsco-manage-resource-page.html, src/company/appsco-company-add-domain.html, src/company/appsco-company-domain-token.html, src/components/account/appsco-account-2fa-enable.html, src/components/account/company/appsco-account-remove.html, src/components/application/appsco-application-details-softwarelicence.html, src/components/application/appsco-application-details.html, src/components/header/appsco-header-account-actions.html, src/components/vault/appsco-vault-details.html
https://webcomputing.jira.com/browse/DASH-2921
=> DASH-2921 External Links using target='_blank'

src/components/components/appsco-list-behavior.html, src/components/resource/appsco-share-resource.html
https://webcomputing.jira.com/browse/DASH-2924
=> DASH-2924 [Front End][Resources] Newly added user does not show up in share resource dialog

index.html, src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2923
=> DASH-2923 Cookie lack Secure flag

src/appsco-customers-page.html
https://webcomputing.jira.com/browse/DASH-2933
=> DASH-2933 Added missing semicolon

src/components/application/appsco-applications.html
https://webcomputing.jira.com/browse/DASH-2931
=> DASH-2931 [Resources] Load more general issue

src/appsco-app.html, src/components/company/appsco-company-twofa-enforced-info.html, src/components/components/appsco-api.html
https://webcomputing.jira.com/browse/DASH-2911
=> DASH-2911 [Front End] Create component to check if you are logged in and 2fa has been enforced during session

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2922
=> DASH-2922 Cookie is not set to be HttpOnly

src/components/account/appsco-account-item.html
https://webcomputing.jira.com/browse/DASH-2937
=> DASH-2937 [Company][Directory] User tab security info for 2fa

src/components/report/appsco-access-report-account-item.html
https://webcomputing.jira.com/browse/DASH-2899
=> DASH-2899 [Front End][Access Report] User access report responsive issue

src/components/components/appsco-list-item-styles.html
https://webcomputing.jira.com/browse/DASH-2910
=> DASH-2910 Long name issue on Account page

src/appsco-app.html, src/components/company/appsco-company-notice.html
https://webcomputing.jira.com/browse/DASH-2911
=> DASH-2911 Info in dialog changed

src/components/customer/appsco-customers-actions.html, src/shared-styles.html
https://webcomputing.jira.com/browse/DASH-2893
=> DASH-2893 [Front End][Customers] Search filter responsive issue

src/directory/appsco-directory-add-account.html
https://webcomputing.jira.com/browse/DASH-2920
=> DASH-2920 [Front End] Invite user to company send activation email toggle should be set to on by default

src/directory/appsco-directory-add-account.html
https://webcomputing.jira.com/browse/DASH-2942
=> DASH-2942 [Front End][Directory] Add info text to Add account to Directory dialog

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-2911
=> DASH-2911 Set interval to check if user has 2fa on 30 seconds

src/company/appsco-company-domain-item.html
https://webcomputing.jira.com/browse/DASH-2956
=> DASH-2956 [Front End][Company Settings] Domains cards responsive

src/components/application/appsco-application-settings.html, src/components/application/company/appsco-company-application-add-settings.html, src/components/application/company/appsco-company-resource-settings.html
https://webcomputing.jira.com/browse/DASH-2944
=> DASH-2944 Enable ftp:// link in link and login resource types

src/appsco-statistics-page.html
https://webcomputing.jira.com/browse/DASH-2900
=> DASH-2900 [Front End][Statistics] Statistics responsive issue

src/application/appsco-dialog-application-add.html, src/applications/appsco-dialog-application-company-add.html, src/components/application/appsco-application-add.html, src/components/application/appsco-application-form-cc.html, src/components/application/appsco-application-form-item.html, src/components/application/appsco-application-form-login.html, src/components/application/appsco-application-form-passport.html, src/components/application/appsco-application-form-securenote.html, src/components/application/appsco-application-form-softwarelicence.html, src/components/application/appsco-application-form-unpw.html, src/components/application/appsco-application-settings.html, src/components/application/company/appsco-company-application-add.html, src/components/application/company/appsco-company-resource-settings.html
https://webcomputing.jira.com/browse/DASH-2934
=> DASH-2934 Text area not text field in Secure note dialog

src/appsco-resources-page.html
https://webcomputing.jira.com/browse/DASH-2951
=> DASH-2951 [Company][Resources] Resources info tab log font issue

src/components/account/appsco-account-log.html, src/components/account/data/locales.json
https://webcomputing.jira.com/browse/DASH-2971
=> DASH-2971 [Company] Promoting / demoting to an admin in activity log

src/application/appsco-resource-image-settings.html
https://webcomputing.jira.com/browse/DASH-2975
=> DASH-2975 Unable to use icon with same name on two resources

src/components/account/appsco-account-notifications.html, src/directory/appsco-manage-account-components-page.html
https://webcomputing.jira.com/browse/DASH-2972
=> DASH-2972 [Front End][Manage Account] User notifications

src/appsco-app.html, src/appsco-manage-account-page.html, src/components/account/appsco-account-log.html
https://webcomputing.jira.com/browse/DASH-2971
=> Dash 2971 [Company] Promoting / demoting to an admin in activity log

src/directory/appsco-manage-account-components-page.html
https://webcomputing.jira.com/browse/DASH-2972
=> DASH-2972 [Front End][Manage Account] User notifications - fixes

src/appsco-app.html, src/appsco-company-page.html, src/company/appsco-company-components-page.html, src/company/appsco-company-transfer-token-page.html, src/company/appsco-company-transfer-token.html, src/components/components/appsco-api-errors.html
https://webcomputing.jira.com/browse/DASH-2996
=> DASH-2996 [Front End][Company Settings] Add Transfer Token card and implement generate token

src/upgrade/appsco-upgrade-action.html
https://webcomputing.jira.com/browse/DASH-2998
=> DASH-2998 Added input for coupon code

src/components/application/company/appsco-company-application-add.html
https://webcomputing.jira.com/browse/DASH-3029
=> DASH-3029 Removed app header when adding app for custom app

src/appsco-app.html, src/appsco-manage-integration-page.html, src/components/integration/appsco-integration-rules-card.html, src/components/integration/appsco-integration-rules.html, src/components/integration/appsco-integration-settings-card.html, src/components/integration/appsco-integration-settings.html, src/components/integration/appsco-integration-webhooks-card.html, src/components/integration/appsco-remove-integration.html, src/provisioning/appsco-integration-rules-page.html, src/provisioning/appsco-integration-settings-page.html, src/provisioning/appsco-manage-integration-components-page.html, src/provisioning/appsco-manage-integration-page-actions.html
https://webcomputing.jira.com/browse/DASH-2960
=> DASH-2960 Created Manage integration page

polymer.json
https://webcomputing.jira.com/browse/DASH-2960
=> DASH-2960 Added url to manage integration page to polymer.json

src/appsco-app.html, src/components/components/appsco-search.html, src/components/components/data/appsco-api-errors.json, src/components/customer/appsco-add-customer.html
https://webcomputing.jira.com/browse/DASH-2995
=> DASH-2995 [Front End][Customers] Add transfer token to add customer dialog

src/appsco-app.html, src/appsco-manage-integration-page.html, src/components/integration/appsco-integration-settings.html, src/components/integration/data/integration-form-data.json, src/provisioning/appsco-integration-settings-page.html, src/provisioning/appsco-manage-integration-components-page.html
https://webcomputing.jira.com/browse/DASH-2968
=> DASH-2968 Created Settings detailed page

bower.json, src/appsco-app.html, src/appsco-manage-integration-page.html, src/appsco-provisioning-page.html, src/provisioning/appsco-add-integration-form.html
https://webcomputing.jira.com/browse/DASH-2955
=> DASH-2955 [Front End][Provisioning] Modify Provisioning page

src/appsco-app.html, src/components/contact/appsco-contacts-actions.html, src/directory/appsco-directory-actions.html
https://webcomputing.jira.com/browse/DASH-3000
=> DASH-3000 [Frontend] Add Notification icon to Directory and Contacts

src/appsco-app.html, src/components/notifications/appsco-send-notification.html
https://webcomputing.jira.com/browse/DASH-2984
=> DASH-2984 [Frontend] Create notification dialog

src/components/components/appsco-search.html, src/components/customer/appsco-add-customer.html
https://webcomputing.jira.com/browse/DASH-2995
=> DASH-2995 [Front End][Customers] Add transfer token to add customer dialog - fixes

src/appsco-app.html, src/appsco-manage-customer-page.html, src/components/customer/appsco-customer-subscription-toggle.html, src/components/customer/appsco-manage-customer-components-page.html
https://webcomputing.jira.com/browse/DASH-2999
=> DASH-2999 [Front End][Manage Customer] Add Customer subscription card and implement action

src/components/group/appsco-company-group-contacts.html, src/components/group/appsco-company-group-resources.html, src/components/group/appsco-company-group-roles.html
https://webcomputing.jira.com/browse/DASH-3051
=> DASH-3051 Load more on groups info bar

src/appsco-app.html
https://webcomputing.jira.com/browse/DASH-3051
=> DASH-3054 Notification toast message typo

src/appsco-app.html, src/appsco-manage-integration-page.html, src/components/components/appsco-list-behavior.html, src/components/components/appsco-list-item-behavior.html, src/components/integration/appsco-integration-rule-item.html, src/components/integration/appsco-integration-rules.html, src/provisioning/appsco-integration-rules-page.html
https://webcomputing.jira.com/browse/DASH-2961
=> DASH-2961 [Front End][Rules] Create Rules detailed page

src/appsco-app.html, src/appsco-manage-customer-page.html, src/components/customer/appsco-customer-subscription-toggle.html, src/components/customer/appsco-disable-customer-subscription-paid-externally.html
https://webcomputing.jira.com/browse/DASH-2999
=> DASH-2999 Implement scenario with confirm dialog

src/applications/appsco-manage-application-components-page.html
https://webcomputing.jira.com/browse/DASH-3058
=> DASH-3058 [Front End][Manage Resource] Fix cards on manage resource page

src/directory/appsco-manage-account-components-page.html
https://webcomputing.jira.com/browse/DASH-3061
=> DASH-3061 [Manage Account] Error when page is reloaded

src/appsco-app.html, src/appsco-provisioning-page.html, src/components/integration/appsco-remove-integration.html, src/provisioning/appsco-active-integrations.html
https://webcomputing.jira.com/browse/DASH-3062
=> DASH-3062 [Front End][Manage Integration] Remove integration not working

src/provisioning/appsco-active-integration-item.html
https://webcomputing.jira.com/browse/DASH-3063
=> DASH-3063 [Frontend] Change integration name title to integration title
