src/appsco-app.html
src/appsco-manage-integration-page.html
src/components/integration/appsco-add-integration-rule.html
src/provisioning/appsco-integration-rules-page.html

https://webcomputing.jira.com/browse/DASH-2966

DASH-2966 [Front End][Rules] Implement Add action on Rules page

---

src/appsco-manage-integration-page.html
src/components/integration/appsco-integration-settings.html
src/provisioning/appsco-integration-settings-page.html

https://webcomputing.jira.com/browse/DASH-2968

DASH-2968 Changed PATCH to PUT, fixed form

---

src/components/integration/appsco-add-integration-rule.html
src/components/integration/appsco-integration-rules.html
src/provisioning/appsco-integration-rules-page.html

https://webcomputing.jira.com/browse/DASH-2966

DASH-2966 From method attribute fixed

---

src/provisioning/appsco-integration-rules-page.html

https://webcomputing.jira.com/browse/DASH-2966

DASH-2966 Item rule style

---

src/appsco-manage-contact-page.html

https://webcomputing.jira.com/browse/DASH-3053

DASH-3053 Shared resources field for contacts does not refresh

---

src/appsco-app.html
src/appsco-manage-integration-page.html
src/components/components/appsco-api-errors.html
src/components/integration/appsco-add-integration-rule.html
src/components/integration/appsco-edit-integration-rule.html
src/components/integration/appsco-integration-rule-item.html
src/components/integration/appsco-integration-rules.html
src/components/integration/appsco-remove-integration-rule.html
src/components/integration/appsco-run-integration-rule.html
src/provisioning/appsco-integration-rules-page.html

https://webcomputing.jira.com/browse/DASH-2962

DASH-2962 [Front End][Rules] Implement Edit and Remove actions

---

src/components/application/appsco-application-add-search.html
src/components/application/appsco-application-add.html
src/components/application/company/appsco-company-application-add-search.html
src/components/application/company/appsco-company-application-add.html

https://webcomputing.jira.com/browse/DASH-3039

DASH-3039 Add custom application modal

---

src/appsco-app.html
src/appsco-manage-integration-page.html
src/components/components/appsco-list-behavior.html
src/components/integration/appsco-integration-webhook-item.html
src/components/integration/appsco-integration-webhooks.html
src/components/integration/appsco-register-integration-webhook.html
src/components/integration/appsco-unregister-integration-webhook.html
src/provisioning/appsco-integration-webhooks-page.html
src/provisioning/appsco-manage-integration-components-page.html

https://webcomputing.jira.com/browse/DASH-2567

DASH-2567 Webhooks page implemented

---

src/appsco-app.html
src/appsco-manage-integration-page.html
src/components/integration/appsco-integration-webhook-item.html
src/components/integration/appsco-integration-webhooks.html
src/components/integration/appsco-register-integration-webhook.html
src/components/integration/appsco-unregister-integration-webhook.html
src/provisioning/appsco-integration-webhooks-page.html

https://webcomputing.jira.com/browse/DASH-2567

DASH-2567 Webhooks update after register action

---

src/components/integration/appsco-integration-webhook-item.html
src/components/integration/appsco-integration-webhooks.html

https://webcomputing.jira.com/browse/DASH-2567

DASH-2567 Webhook icon changed to av:call-to-action

---

src/components/integration/appsco-integration-webhook-item.html
src/components/integration/appsco-integration-webhooks.html

https://webcomputing.jira.com/browse/DASH-2567

DASH-2567 Webhook state after unregister action

---

src/appsco-app.html
src/components/customer/appsco-customer-subscription-toggle.html
src/components/customer/appsco-toggle-customer-subscription-paid-externally.html

https://webcomputing.jira.com/browse/DASH-3073

DASH-3073 Partner billing confirmation issues

---

src/appsco-resources-page.html

https://webcomputing.jira.com/browse/DASH-3050

DASH-3050 [Front End] Groups left toolbar should be unified for resources and contacts

---

src/components/application/appsco-application-add-search.html
src/components/application/company/appsco-company-application-add-search.html
src/components/application/company/appsco-company-application-sso-list.html
src/components/group/appsco-group-add-resource.html

https://webcomputing.jira.com/browse/DASH-3083

DASH-3083 Application search issue

---

src/appsco-app.html

https://webcomputing.jira.com/browse/DASH-3084

DASH-3084 [Front End][Personal] Personal switch to company name

---

src/appsco-app.html
src/appsco-customers-page.html
src/appsco-directory-page.html
src/appsco-groups-page.html
src/appsco-resources-page.html
src/components/application/appsco-application-actions.html
src/components/customer/appsco-customers-actions.html
src/components/group/appsco-group-actions.html
src/directory/appsco-directory-actions.html

https://webcomputing.jira.com/browse/DASH-3087

DASH-3087 [Front End] Select all functionality for all card lists

---

src/appsco-audit-log-page.html

https://webcomputing.jira.com/browse/DASH-3088

DASH-3088 [Audit log] Event type filter should be sorted by alphabet

---

src/appsco-audit-log-page.html

https://webcomputing.jira.com/browse/DASH-3089

DASH-3089 [Front End][Audit Log] Event type filter duplicate result

---

src/appsco-app.html
src/appsco-audit-log-page.html
src/auditlog/appsco-audit-log.html

https://webcomputing.jira.com/browse/DASH-3090

DASH-3090 [Audit Log] From/To filters default value

---

src/appsco-manage-integration-page.html

https://webcomputing.jira.com/browse/DASH-3072

DASH-3072 [Front End][Manage Integration] Add link field to resource section

---

src/components/resource/appsco-share-resource.html

https://webcomputing.jira.com/browse/DASH-3068

DASH-3068 [Resources] Search account in share resource dialog should not be case sensitive

---

src/appsco-directory-page.html

https://webcomputing.jira.com/browse/DASH-3067

DASH-3067 [Company][Directory] No invitations info message

---

src/appsco-app.html

https://webcomputing.jira.com/browse/DASH-3047

DASH-3047 Remove calls from billing if customer is set to paid externally

---

src/appsco-app.html

https://webcomputing.jira.com/browse/DASH-3065

DASH-3065 [Company][Customers] Export to CSV not working

---

src/account/appsco-account-page-actions.html
src/application/appsco-resource-page-actions.html
src/applications/appsco-manage-resource-page-actions.html
src/components/contact/appsco-manage-contact-page-actions.html
src/components/customer/appsco-manage-customer-page-actions.html
src/components/group/appsco-manage-group-page-actions.html
src/components/report/appsco-access-report-actions.html
src/components/report/appsco-access-report-page-actions.html
src/directory/appsco-manage-account-page-actions.html
src/provisioning/appsco-manage-integration-page-actions.html
src/shared-styles.html

https://webcomputing.jira.com/browse/DASH-3041

DASH-3041 Back button and horizontal line inconsistency

---

src/components/application/company/appsco-company-application-sso-list.html
src/components/application/company/appsco-company-resource-item.html
src/components/application/company/appsco-company-sso-application-add.html
src/components/components/appsco-list-item-styles.html

https://webcomputing.jira.com/browse/DASH-3069

DASH-3069 [Front End] New app select dialog for SSO applications

---

src/components/account/appsco-account-notifications.html
src/components/components/appsco-list-item.html

https://webcomputing.jira.com/browse/DASH-3055

DASH-3055 Notification - sender information

---

bower.json
src/appsco-app.html
src/components/company-role/appsco-role-save-client-data.html

https://webcomputing.jira.com/browse/DASH-3017

DASH-3017 [Frontend] Collect and send information about user to API

---

src/appsco-audit-log-page.html

https://webcomputing.jira.com/browse/DASH-3096

DASH-3096 [Company][Audit] Default event type

---

src/appsco-app.html
src/appsco-manage-account-page.html
src/components/account/company/appsco-account-approve-device.html
src/components/account/company/appsco-account-devices-item.html
src/components/account/company/appsco-account-devices.html
src/components/account/company/appsco-account-disapprove-device.html
src/directory/appsco-account-devices-page.html
src/directory/appsco-manage-account-components-page.html

https://webcomputing.jira.com/browse/DASH-3018

DASH-3018 [Frontend] Create Device card under user

---

src/components/orgunit/appsco-orgunit-remove.html

https://webcomputing.jira.com/browse/DASH-3075

DASH-3075 Buggy remove org unit logic when user is attached

---

src/appsco-app.html
src/appsco-audit-log-page.html
src/auditlog/appsco-audit-log-actions.html
src/auditlog/appsco-audit-log-page-actions.html
src/auditlog/appsco-audit-log.html

https://webcomputing.jira.com/browse/DASH-3092

DASH-3092 [Backend][API] Implement route for export Audit log

---

src/auditlog/appsco-audit-log.html
src/auditlog/data/locales.json
src/components/account/appsco-account-log.html

Writing logs in company log, account log and application log are changed in order to use elasticsearch.

DASH-2979 Migrate existing data to elastic search

---

src/components/company-role/appsco-role-save-client-data.html

https://webcomputing.jira.com/browse/DASH-3017

DASH-3017 Check if account is admin of the company

---

src/components/account/appsco-account-log.html

https://webcomputing.jira.com/browse/DASH-2979

DASH-2979 - fxes

---

src/appsco-app.html
src/appsco-resource-page.html

https://webcomputing.jira.com/browse/DASH-3086

DASH-3086 [Personal][Manage resource] Change resource image

---

src/provisioning/appsco-integration-webhooks-page.html

https://webcomputing.jira.com/browse/DASH-3070

DASH-3070 [Provisioning] Implement Active Directory as Request Authority in Provisioning

---

src/auditlog/appsco-audit-log.html
src/auditlog/data/locales.json

https://webcomputing.jira.com/browse/DASH-3110

DASH-3110 [Company][Audit] Empty log entries issues

---

src/appsco-app.html
src/company/appsco-company-add-certificate.html
src/company/appsco-company-idp-settings-certificate-item.html
src/company/appsco-company-idp-settings-certificates.html
src/company/appsco-company-idp-settings.html

https://webcomputing.jira.com/browse/DASH-3035

DASH-3035 Office 365 certificate problem for Alliance

---

src/auditlog/appsco-audit-log.html

https://webcomputing.jira.com/browse/DASH-3114

DASH-3114 [Company][Audit] Long username

---

src/directory/appsco-manage-account-components-page.html

https://webcomputing.jira.com/browse/DASH-3098

DASH-3098 [Company] Org unit long names

---

src/appsco-billing-page.html

https://webcomputing.jira.com/browse/DASH-3102

DASH-3102 [Front End][Billing] Invoice info section showing test address

---

src/appsco-audit-log-page.html
src/auditlog/appsco-audit-log.html

https://webcomputing.jira.com/browse/DASH-3113

DASH-3113 [Company][Audit] Audit log refreshing

---

src/application/appsco-resource-image-settings.html
src/appsco-app.html
src/company/appsco-company-image-settings.html
src/components/account/appsco-account-image-settings.html

https://webcomputing.jira.com/browse/DASH-3095

DASH-3095 Incorrect file type message

---

src/components/report/appsco-access-report-page-filters.html

https://webcomputing.jira.com/browse/DASH-3099

DASH-3099 [Company] Access-report - filter by group

---

src/auditlog/appsco-audit-log.html

https://webcomputing.jira.com/browse/DASH-3117

DASH-3117 [Company][Audit] Create resource audit log entry

---

src/appsco-manage-integration-page.html

https://webcomputing.jira.com/browse/DASH-3072

DASH-3072 - fixes

---

src/appsco-billing-page.html

https://webcomputing.jira.com/browse/DASH-3118

DASH-3118 [Front End][Billing] Change AppsCo address on invoice

---

src/auditlog/appsco-audit-log.html

https://webcomputing.jira.com/browse/DASH-3121

DASH-3121 [Company][Audit] Refreshing the audit page

---

src/appsco-audit-log-page.html
src/auditlog/appsco-audit-log.html

https://webcomputing.jira.com/browse/DASH-3127

DASH-3127 [Front End][Audit Log] Defatult Date from/Date to not filtering properly

---

src/appsco-audit-log-page.html

https://webcomputing.jira.com/browse/DASH-3136

DASH-3136 [Company][Audit] Refreshing issue

---

src/components/application/company/appsco-company-resource-settings.html

https://webcomputing.jira.com/browse/DASH-3134

DASH-3134 [Company][Resources] Clicking save on 'Set Individually'

---

src/auditlog/appsco-audit-log.html
src/auditlog/data/locales.json
src/components/components/data/event-types.json

https://webcomputing.jira.com/browse/DASH-3031

DASH-3031 Add event to Audit log - Managed account logging in to Appsco

---

src/components/application/company/appsco-company-resource-item.html

https://webcomputing.jira.com/browse/DASH-3147

DASH-3147 [Front End][Resources] Add SSO saml resource dialog should not include multi-select

---

src/appsco-audit-log-page.html

https://webcomputing.jira.com/browse/DASH-3154

DASH-3154 [Front][Audit Log] From date is not set properly

---

src/appsco-app.html
src/appsco-company-page.html
src/company/appsco-company-transfer-token-page.html
src/company/appsco-company-transfer-token.html
src/components/components/appsco-api.html

https://webcomputing.jira.com/browse/DASH-3105

DASH-3105 [Front End][Company Settings] Create drop-down to list all AppsCo partners and send functionality

---

src/auditlog/appsco-audit-log.html
src/auditlog/data/locales.json
src/components/components/data/event-types.json

https://webcomputing.jira.com/browse/DASH-3032

DASH-3032 Login attempts by contacts doesnt seem to log to audit log

---

src/appsco-app.html
src/appsco-contacts-page.html
src/appsco-customers-page.html
src/appsco-directory-page.html
src/appsco-groups-page.html
src/appsco-resources-page.html
src/components/application/appsco-application-actions.html
src/components/components/all-imports.html
src/components/components/appsco-page-behavior.html
src/components/contact/appsco-contacts-actions.html
src/components/customer/appsco-customers-actions.html
src/components/group/appsco-company-groups.html
src/components/group/appsco-group-actions.html
src/directory/appsco-directory-actions.html
src/directory/appsco-directory-page-actions.html

https://webcomputing.jira.com/browse/DASH-3139

DASH-3139 [Front End] Select all should be visible at all times

---

src/auditlog/appsco-audit-log.html
src/auditlog/data/locales.json
src/components/components/data/event-types.json

https://webcomputing.jira.com/browse/DASH-3109

DASH-3109 Add event to Audit log - Implement transfer token sent event

---

src/appsco-manage-account-page.html
src/directory/appsco-manage-account-components-page.html
src/directory/appsco-manage-account-twofa-page.html

https://webcomputing.jira.com/browse/DASH-3156

DASH-3156 [Frontend][Manage account] 2FA Should be editable by company admin

---

src/appsco-app.html
src/appsco-company-page.html
src/company/appsco-company-settings-page.html
src/company/appsco-company-settings.html

https://webcomputing.jira.com/browse/DASH-3023

DASH-3023 [Frontent] Extend Company settings with fields

---

src/appsco-app.html
src/components/oauth-application/appsco-add-oauth-application.html

https://webcomputing.jira.com/browse/DASH-3012

DASH-3012 [Frontend] Register OAuth application

---

src/provisioning/appsco-add-integration-search.html
src/provisioning/appsco-add-integration.html
src/provisioning/appsco-available-integration-item.html

https://webcomputing.jira.com/browse/DASH-3146

DASH-3146 [Front End] Change Add Integration dialog

---

src/company/appsco-company-transfer-token.html

https://webcomputing.jira.com/browse/DASH-3157

DASH-3157 Transfer token issue

---

src/appsco-app.html
src/appsco-oauth-applications-page.html
src/components/components/appsco-list-behavior.html
src/components/oauth-application/appsco-oauth-application-details.html
src/components/oauth-application/appsco-oauth-applications-actions.html
src/components/oauth-application/appsco-oauth-applications-item.html
src/components/oauth-application/appsco-oauth-applications-page-actions.html
src/components/oauth-application/appsco-oauth-applications.html
src/components/oauth-application/appsco-remove-oauth-application.html

https://webcomputing.jira.com/browse/DASH-3010

DASH-3010 [Frontend] OAuth applications page

---

polymer.json
src/appsco-app.html
src/appsco-manage-oauth-application-page.html
src/appsco-oauth-applications-page.html
src/company/appsco-company-idp-settings.html
src/components/components/appsco-list-behavior.html
src/components/oauth-application/appsco-add-oauth-application-certificate.html
src/components/oauth-application/appsco-edit-oauth-application-form.html
src/components/oauth-application/appsco-manage-oauth-application-components-page.html
src/components/oauth-application/appsco-manage-oauth-application-page-actions.html
src/components/oauth-application/appsco-oauth-application-authorizations.html
src/components/oauth-application/appsco-oauth-application-certificate-item.html
src/components/oauth-application/appsco-oauth-application-certificates-page.html
src/components/oauth-application/appsco-oauth-application-certificates.html
src/components/oauth-application/appsco-oauth-application-details.html
src/components/oauth-application/appsco-oauth-application-info.html
src/components/oauth-application/appsco-oauth-application-settings-page.html
src/components/oauth-application/appsco-oauth-applications-item.html
src/components/oauth-application/appsco-oauth-applications.html
src/components/oauth-application/appsco-remove-oauth-application-certificate.html
src/components/oauth-application/appsco-remove-oauth-application.html
src/components/oauth-application/appsco-upload-oauth-application-icon.html
src/provisioning/appsco-integration-form.html
src/shared-styles.html

https://webcomputing.jira.com/browse/DASH-3009

DASH-3009 [Frontend] Manage OAuth app page

---

src/appsco-manage-oauth-application-page.html
src/appsco-oauth-applications-page.html
src/components/oauth-application/appsco-edit-oauth-application-form.html
src/components/oauth-application/appsco-oauth-application-info.html

https://webcomputing.jira.com/browse/DASH-3182

DASH-3182 [OAuth applications feature] Improvements needed

---

src/components/account/company/appsco-account-orgunit.html

https://webcomputing.jira.com/browse/DASH-3181

DASH-3181 [Frontend][Directory] Add users to organization unit dialog

---

src/appsco-billing-page.html

https://webcomputing.jira.com/browse/DASH-3176

DASH-3176 Investigate billing page issue with new companies

---

src/company/appsco-company-settings.html

https://webcomputing.jira.com/browse/DASH-3186

DASH-3186 [Company][Settings] Ip whitelist issue

---

src/appsco-oauth-applications-page.html

https://webcomputing.jira.com/browse/DASH-3189

DASH-3189 [Frontend][OAuth] Add text to resource section

---

src/components/oauth-application/appsco-oauth-application-info.html

https://webcomputing.jira.com/browse/DASH-3182

DASH-3182 OAuth application info fixed

---

src/appsco-app.html

https://webcomputing.jira.com/browse/DASH-3188

DASH-3188 [Frontend][OAuth] Rename page title and placing in the menu

---

src/components/components/data/appsco-api-errors.json

https://webcomputing.jira.com/browse/DASH-3190

DASH-3190 [Company][OAuth Applications] Add certificate issue

---

src/appsco-app.html

https://webcomputing.jira.com/browse/DASH-3200

DASH-3200 When integration title is changed back end does not update before refresh

---

src/appsco-app.html

https://webcomputing.jira.com/browse/DASH-2976

DASH-2976 Redirected to wrong dashboard on login

---

src/company/appsco-company-settings.html

https://webcomputing.jira.com/browse/DASH-3193

DASH-3193 Disapprove mobile logins

---

src/components/orgunit/appsco-orgunit-tree-node.html

https://webcomputing.jira.com/browse/DASH-3210

DASH-3210 Remove main organization unit causes error

---

src/provisioning/appsco-add-integration-search.html
src/provisioning/appsco-add-integration.html

https://webcomputing.jira.com/browse/DASH-3221

DASH-3221 [Company][Provisioning] Warning when I click on add

---

src/applications/appsco-resources-page-actions.html
src/appsco-app.html
src/appsco-contacts-page.html
src/appsco-customers-page.html
src/appsco-directory-page.html
src/appsco-groups-page.html
src/appsco-resources-page.html
src/components/account/appsco-accounts.html
src/components/account/appsco-contacts.html
src/components/account/appsco-invitations.html
src/components/application/appsco-application-actions.html
src/components/application/company/appsco-company-resources.html
src/components/components/appsco-list-behavior.html
src/components/components/appsco-list-observer-behavior.html
src/components/contact/appsco-contacts-actions.html
src/components/contact/appsco-contacts-page-actions.html
src/components/customer/appsco-customers-actions.html
src/components/customer/appsco-customers-page-actions.html
src/components/customer/appsco-customers.html
src/components/group/appsco-company-groups.html
src/components/group/appsco-group-actions.html
src/components/group/appsco-groups-page-actions.html
src/directory/appsco-directory-actions.html
src/directory/appsco-directory-page-actions.html

https://webcomputing.jira.com/browse/DASH-3179

DASH-3179 Select all action opening bulk actions even if there are no elements on page

---

src/appsco-audit-log-page.html

https://webcomputing.jira.com/browse/DASH-3227

DASH-3227 [Audit Log] Default FROM date in Audit log not set

---

src/appsco-statistics-page.html

https://webcomputing.jira.com/browse/DASH-3207

DASH-3207 [Company][Statistics] Application usage not showing data

---

src/appsco-audit-log-page.html
src/auditlog/appsco-audit-log.html
src/auditlog/data/locales.json
src/components/components/data/event-types.json

https://webcomputing.jira.com/browse/DASH-3175

DASH-3175 [Frontend][Audit log] Implement log events for OAuth applications

---

bower.json
src/appsco-app.html
src/appsco-company-home-page.html
src/company/appsco-company-home-page-actions.html
src/components/application/appsco-application-item.html
src/components/application/appsco-applications.html
src/components/components/appsco-api.html
src/components/folder/appsco-add-folder.html
src/components/folder/appsco-folders-application-add.html
src/components/folder/appsco-folders-item.html
src/components/vaadin-context-menu/vaadin-context-menu-override.html

https://webcomputing.jira.com/browse/DASH-3168

DASH-3168 [Frontend][Dashboard] Implement right click and move action

---

src/components/account/appsco-account-log-item.html
src/components/account/appsco-account-log.html
src/components/account/data/locales.json

https://webcomputing.jira.com/browse/DASH-3208

DASH-3208 [Company] Group logs issues

---

src/provisioning/appsco-add-integration.html
src/provisioning/appsco-integration-form.html

https://webcomputing.jira.com/browse/DASH-3149

DASH-3149 [Backend] Provisioning - Egnyte as PST

---

src/components/account/appsco-account-details.html
src/components/account/appsco-invitations.html

https://webcomputing.jira.com/browse/DASH-3259

DASH-3259 [Company][Directory] Error on page

---

src/appsco-app.html

https://webcomputing.jira.com/browse/DASH-3179

DASH-3179 - fixes

---

src/appsco-app.html

https://webcomputing.jira.com/browse/DASH-3258

DASH-3258 [Company][Audit log] Error on page

---

src/account/appsco-account-components-page.html
src/account/appsco-account-notifications-page.html
src/appsco-app.html
src/components/account/appsco-account-notifications.html
src/components/components/appsco-api.html
src/components/header/appsco-account-notifications-dropdown.html
src/components/header/appsco-header-account-actions.html
src/components/header/appsco-header.html
src/directory/appsco-manage-account-components-page.html

https://webcomputing.jira.com/browse/DASH-3187

Dash 3187 [Personal][Notifications] No indication that notification has been received

---

src/appsco-app.html

https://webcomputing.jira.com/browse/DASH-3215

DASH-3215 [Frontend][Company] Sectionize the menu

---

src/components/account/appsco-account-log.html

https://webcomputing.jira.com/browse/DASH-3264

DASH-3264 [Personal] Activity log issues

---

polymer.json
src/appsco-app.html
src/appsco-customer-billing-page.html

https://webcomputing.jira.com/browse/DASH-3222

DASH-3222 [Frontend][Customer Billing] Create Customer Billing page and add it to menu

---

src/company/appsco-company-domain-item.html

https://webcomputing.jira.com/browse/DASH-3267

DASH-3267 [Company][Settings] Domain - created at

---

src/appsco-app.html
src/appsco-billing-page.html
src/appsco-customer-billing-page.html
src/billing/appsco-update-subscription-action.html

https://webcomputing.jira.com/browse/DASH-3223

DASH-3223 [Frontend][Customer Billing] Create subscription plan card

---

src/appsco-app.html
src/appsco-billing-page.html
src/appsco-customer-billing-page.html

https://webcomputing.jira.com/browse/DASH-3231

DASH-3231 [Frontend][Customer Billing] Create invoice list

---

src/appsco-app.html
src/appsco-billing-page.html
src/billing/appsco-subscription-cancel.html
src/upgrade/appsco-upgrade-action.html

https://webcomputing.jira.com/browse/DASH-3225

DASH-3225 [Frontend][Billing] Refactor Billing so it checks for subscription

---

src/appsco-billing-page.html

https://webcomputing.jira.com/browse/DASH-3225

DASH-3225 [Frontend][Billing] - invoice list api route fixed

---

polymer.json
src/appsco-app.html
src/appsco-dashboard-folder-page.html
src/components/application/appsco-applications.html
src/components/components/appsco-drag-html-element-behavior.html
src/components/components/appsco-drop-html-element-behavior.html
src/components/components/appsco-list-behavior.html
src/components/components/appsco-list-item-styles.html
src/components/folder/appsco-add-folder.html
src/components/folder/appsco-dashboard-folder-page-actions.html
src/components/folder/appsco-folders-application-add.html
src/components/folder/appsco-folders-item.html
src/components/folder/appsco-folders.html

https://webcomputing.jira.com/browse/DASH-3166

DASH-3166 [Frontend][Dashboard] Implement drag and drop on Dashboard

---

src/appsco-app.html
src/appsco-saml-authn-request-invalid-page.html

https://webcomputing.jira.com/browse/DASH-3289

DASH-3289 [FRONTEND] Create page for unatuhorized saml request

---

polymer.json

https://webcomputing.jira.com/browse/DASH-3289

DASH-3289 Added page to polymer.json

---

src/application/appsco-application-settings-dialog.html
src/appsco-app.html
src/appsco-billing-page.html
src/appsco-customer-billing-page.html
src/billing/appsco-billing-send-invoice.html

https://webcomputing.jira.com/browse/DASH-3232

DASH-3232 [Backend] Implement Customer billing invoice email

---

src/appsco-app.html
src/appsco-company-home-page.html
src/appsco-dashboard-folder-page.html
src/components/folder/appsco-folders-item.html

https://webcomputing.jira.com/browse/DASH-3292

DASH-3166 Do not show folders if there are none in company

---

src/appsco-app.html
src/appsco-company-home-page.html
src/appsco-dashboard-folder-page.html
src/company/appsco-company-home-page-actions.html
src/components/folder/appsco-dashboard-folder-page-actions.html

https://webcomputing.jira.com/browse/DASH-3166

DASH-3166 Dashboard Folder page: list applications inside

---

src/components/components/appsco-drag-html-element-behavior.html

https://webcomputing.jira.com/browse/DASH-3166

DASH-3166 Drag behavior fixed for FF

---

src/appsco-app.html
src/appsco-company-home-page.html
src/appsco-dashboard-folder-page.html
src/components/components/appsco-drag-html-element-behavior.html

https://webcomputing.jira.com/browse/DASH-3167

DASH-3167 [Frontend][Dashboard folder] Implement breadcrumbs when inside a folder

---

src/appsco-app.html
src/appsco-company-home-page.html
src/components/components/data/appsco-api-errors.json
src/components/folder/appsco-folders-item.html
src/components/folder/appsco-folders-remove.html
src/components/folder/appsco-folders-rename.html
src/components/folder/appsco-folders.html

https://webcomputing.jira.com/browse/DASH-3169

DASH-3169 [Frontend][Dashboard] Rename and remove on dashboard folder

---

src/appsco-app.html
src/appsco-dashboard-folder-page.html
src/components/application/appsco-applications.html
src/components/folder/appsco-folders-application-add.html
src/components/folder/appsco-folders-item.html

https://webcomputing.jira.com/browse/DASH-3297

DASH-3297 [Front end] Bug when moving resources into multiple folders and then removing

---

src/applications/appsco-resources-page-actions.html
src/components/application/appsco-application-actions.html
src/directory/appsco-directory-page-actions.html

https://webcomputing.jira.com/browse/DASH-3266

DASH-3266 [Company][Directory] Search bar responsivness

---

src/provisioning/appsco-integration-form.html

https://webcomputing.jira.com/browse/DASH-3295

DASH-3295 [Company][Provisioning] Invalid url warning

---

src/appsco-app.html
src/appsco-directory-page.html

https://webcomputing.jira.com/browse/DASH-3310

DASH-3310 Subscription issue

---

src/appsco-app.html

https://webcomputing.jira.com/browse/DASH-3299

DASH-3299 Notification does not remove from plugin

---

src/appsco-app.html
src/components/application/appsco-application-actions.html

https://webcomputing.jira.com/browse/DASH-3301

DASH-3301 [Frontend][Personal] Remove filters on Personal dashboard

---

src/directory/appsco-directory-add-account.html

https://webcomputing.jira.com/browse/DASH-3242

DASH-3242 [Company]Adding a managed user to a company

---

src/applications/appsco-application-compliance-page.html
src/applications/appsco-manage-application-components-page.html
src/appsco-app.html
src/appsco-manage-resource-page.html

https://webcomputing.jira.com/browse/DASH-3276

DASH-3276 [Frontend][Manage Resource] Add Compliance card and page

---

src/appsco-app.html

https://webcomputing.jira.com/browse/DASH-3307

DASH-3307 [Frontend] Revoke resources shared from non-native companies

---

src/appsco-app.html
src/appsco-compliance-report-page.html
src/components/report/appsco-compliance-report-account-item.html
src/components/report/appsco-compliance-report-account-resource-item.html
src/components/report/appsco-compliance-report-accounts.html
src/components/report/appsco-compliance-report-page-filters.html

https://webcomputing.jira.com/browse/DASH-3278

DASH-3278 [Frontend][Compliance report] Create Compliance report page

---

src/appsco-customer-billing-page.html

https://webcomputing.jira.com/browse/DASH-3315

DASH-3315 [Frontend][Customer Billing] Add number of remaining licences to Customer Billing

---

src/application/appsco-home-page-actions.html
src/appsco-app.html
src/appsco-company-home-page.html
src/appsco-dashboard-folder-page.html
src/appsco-home-page.html
src/components/folder/appsco-add-folder.html

https://webcomputing.jira.com/browse/DASH-3302

DASH-3302 [Frontend][Personal] Implement dashboard folders on personal

---

src/appsco-app.html
src/components/report/appsco-compliance-report-actions.html
src/components/report/appsco-compliance-report-page-actions.html

https://webcomputing.jira.com/browse/DASH-3280

DASH-3280 [Frontend][Compliance report] Implement export compliance report

---

src/components/application/appsco-application-actions.html

https://webcomputing.jira.com/browse/DASH-3325

DASH-3325 [Company][Home] Error on dashboard

---

src/components/customer/appsco-manage-customer-subscription.html

https://webcomputing.jira.com/browse/DASH-3338

DASH-3338 [Frontend][Manage Customer] Error message falling out

---

src/appsco-app.html
src/appsco-reports-page.html
src/components/report/appsco-report-details.html
src/components/report/appsco-report-item.html
src/components/report/appsco-reports-list.html

https://webcomputing.jira.com/browse/DASH-3277

DASH-3277 [Frontend][Reports] Add Compliance report to reports page

---

src/appsco-app.html
src/appsco-reports-page.html
src/components/report/appsco-report-details.html
src/components/report/appsco-report-item.html
src/components/report/appsco-reports-list.html

https://webcomputing.jira.com/browse/DASH-3281

DASH-3281 [Frontend][Reports] Implement export compliance report

---

src/applications/appsco-application-compliance-page.html

https://webcomputing.jira.com/browse/DASH-3351

DASH-3351 [Frontend][Manage Resource] Compliance card info text

---

src/appsco-app.html

https://webcomputing.jira.com/browse/DASH-3343

DASH-3343 [Front end] Application missing in folder if added right after shared

---

polymer.json

https://webcomputing.jira.com/browse/DASH-3349

DASH-3349 [Frontend]Compliance report

---

src/components/customer/appsco-customer-item.html

https://webcomputing.jira.com/browse/DASH-3355

DASH-3355 [Customers] Status on customer card always showing trial

---

src/appsco-app.html
src/appsco-contact-home-page.html

https://webcomputing.jira.com/browse/DASH-3356

DASH-3356 Revoke resource shared to contacts not working on company dashboard

---

src/components/components/appsco-list-behavior.html
src/provisioning/appsco-add-integration-search.html
src/provisioning/appsco-add-integration.html
src/provisioning/appsco-integration-form.html

https://webcomputing.jira.com/browse/DASH-3346

DASH-3346 Implement Provisioning for HIPAA COMPLETE

---

src/appsco-resources-page.html
src/components/application/appsco-applications.html
src/components/components/appsco-list-behavior.html

https://webcomputing.jira.com/browse/DASH-3350

DASH-3350 Set min search term length for apps and lists to 2

---

src/account/appsco-account-components-page.html
src/appsco-app.html
src/components/application/appsco-import-personal-resources.html

https://webcomputing.jira.com/browse/DASH-3329

DASH-3329 [Frontend][Account] Add import from LastPass on Account

---

src/appsco-app.html
src/appsco-billing-report-page.html

https://webcomputing.jira.com/browse/DASH-3246

DASH-3246 [Frontend][Billing Report] Create Billing report page

---

src/appsco-account-page.html
src/appsco-app.html
src/components/account/appsco-account-remove-personal.html
src/components/components/appsco-api.html

https://webcomputing.jira.com/browse/DASH-3332

DASH-3332 [Personal] Add support for delete account on Personal

---

src/components/account/appsco-account-settings.html

https://webcomputing.jira.com/browse/DASH-3320

DASH-3320 [Frontend][My Account] Add Email notifications toggle

---

src/applications/appsco-application-compliance-page.html

https://webcomputing.jira.com/browse/DASH-3360

DASH-3360 Fixed grammatical error on resource compliance page

---

src/components/customer/appsco-customer-subscription-toggle.html
src/components/customer/appsco-manage-customer-components-page.html

https://webcomputing.jira.com/browse/DASH-3353

DASH-3353 [Manage Customer] Add the number of customer licences curently in use number on

---

src/provisioning/appsco-add-integration-form.html
src/provisioning/appsco-integration-form.html

https://webcomputing.jira.com/browse/DASH-3348

DASH-3348 [Provisioning] Integration with Zendesk

---

src/appsco-customer-billing-page.html

https://webcomputing.jira.com/browse/DASH-3357

DASH-3357 [Frontend][Customer Billing] Add Cancel subscription on Customer Billing when Partner pays by cc

---

src/appsco-app.html
src/appsco-billing-report-page.html
src/components/customer/appsco-customer-billing-item.html
src/components/customer/appsco-customers-billing.html

https://webcomputing.jira.com/browse/DASH-3243

DASH-3243 [Frontend][Billing Report] Create customers list

---

src/components/customer/appsco-customer-billing-item.html
src/provisioning/appsco-integration-form.html

https://webcomputing.jira.com/browse/DASH-3347

DASH-3347 [Provisioning] Integration with Pipedrive

---

src/applications/appsco-application-compliance-page.html

https://webcomputing.jira.com/browse/DASH-3404

DASH-3404 [Frontend] Compliance info manage form error

---

src/appsco-app.html
src/appsco-billing-report-page.html
src/components/report/appsco-billing-report-actions.html
src/components/report/appsco-billing-report-page-actions.html

https://webcomputing.jira.com/browse/DASH-3250

DASH-3250 [Frontend][Billing Report] Implement Export report

---

src/components/customer/appsco-customers-billing.html

https://webcomputing.jira.com/browse/DASH-3419

DASH-3419 [Partner][Billing Report] Customers not showing on Billing Report page

---

src/appsco-company-home-page.html

https://webcomputing.jira.com/browse/DASH-3403

DASH-3403 Folder section remains when switching from dashboard with folders to one without.

---

src/appsco-app.html
src/components/customer/appsco-add-partner-admin.html

https://webcomputing.jira.com/browse/DASH-3417

DASH-3417 [Frontend][Manage Customer] Add partner admin dialog issue

---

src/appsco-app.html
src/appsco-company-home-page.html
src/appsco-home-page.html

https://webcomputing.jira.com/browse/DASH-3412

DASH-3412 [Resources] Edit resource not showing on Info section

---

src/company/appsco-company-settings.html

https://webcomputing.jira.com/browse/DASH-3375

DASH-3375 Extend company settings model system admin email

---

src/appsco-app.html
src/components/group/appsco-company-group-notification-dialog.html
src/components/group/appsco-group-actions.html
src/components/group/appsco-group-list-item.html

https://webcomputing.jira.com/browse/DASH-3364

DASH-3364 [Frontend][Groups] Add notification icon in action header and implement action

---

src/components/account/appsco-account-image.html

https://webcomputing.jira.com/browse/DASH-3430

DASH-3430 [Frontend][Manage Customer] Profile image on partner admin list

---

src/appsco-app.html
src/components/header/appsco-header-account-actions.html
src/components/header/appsco-header.html
src/components/notifications/appsco-notification-icon.html

https://webcomputing.jira.com/browse/DASH-3365

DASH-3365 [Frontend][Notification] Modify notifications to show notifications as numbers

---

src/components/integration/appsco-add-integration-rule.html
src/components/integration/appsco-edit-integration-rule.html
src/components/integration/appsco-integration-rules-operators.html

https://webcomputing.jira.com/browse/DASH-3434

DASH-3434 [Provisioning] Implement support from provisioning of AppsCo Groups to other systems

---

src/components/resource/appsco-share-resource.html
src/provisioning/appsco-add-integration.html

https://webcomputing.jira.com/browse/DASH-3435

DASH-3435 [Frontend] Buttons in dialogs not visible if the screen height is smaller

---

src/components/components/data/appsco-api-errors.json

https://webcomputing.jira.com/browse/DASH-3437

DASH-3437 [Backend] SSO resource can be shared to unmanaged users

---

src/appsco-company-page.html

https://webcomputing.jira.com/browse/DASH-3440

DASH-3440 [Company Settings] Add company URL to resource section

---

src/appsco-app.html
src/appsco-company-page.html
src/company/appsco-company-branded-login-page.html

https://webcomputing.jira.com/browse/DASH-3438
https://appscoinc.atlassian.net/browse/DASH-3440

DASH-3438 [Frontend][Company Settings] Branded login card does not close after save

---

src/appsco-audit-log-page.html

https://appscoinc.atlassian.net/browse/DASH-3441

DASH-3441 [Frontend][Audit log] Bug when filtering audit log

---

src/auditlog/appsco-audit-log.html
src/auditlog/data/locales.json
src/components/components/data/event-types.json

https://appscoinc.atlassian.net/browse/DASH-3392

DASH-3392 [BACKEND][Policy] Disapprove personal dashboard

---

polymer.json
src/appsco-app.html
src/appsco-policies-page.html
src/components/components/appsco-list-behavior.html
src/components/policy/appsco-change-policy-status.html
src/components/policy/appsco-ip-whitelist-policy-settings.html
src/components/policy/appsco-policies-page-actions.html
src/components/policy/appsco-policies.html
src/components/policy/appsco-policy-info.html
src/components/policy/appsco-policy-item.html
src/components/policy/appsco-policy-settings.html
src/components/policy/data/policy-info.json

https://appscoinc.atlassian.net/browse/DASH-3381

DASH-3381 [Frontend][Policies] Create policies page and implement actions

---

src/appsco-app.html
src/appsco-page-styles.html
src/appsco-reports-page.html
src/components/report/appsco-report-details.html

https://appscoinc.atlassian.net/browse/DASH-3383

DASH-3383 [Frontend][Reports] Create Policies report

---

polymer.json
src/appsco-app.html
src/appsco-policies-page.html
src/appsco-policies-report-page.html
src/components/components/appsco-list-behavior.html
src/components/report/appsco-policies-report-breached-policy-item.html
src/components/report/appsco-policy-report-actions.html
src/components/report/appsco-policy-report-page-actions.html
src/components/report/appsco-policy-report-page-filters.html
src/components/report/appsco-policy-report-role-item.html
src/components/report/appsco-policy-report-roles.html

https://appscoinc.atlassian.net/browse/DASH-3384

DASH-3384 [Frontend][Policy report] Implement policy report

---

src/appsco-app.html

https://appscoinc.atlassian.net/browse/DASH-3384

DASH-3384 Export Policy Report events updated

---

src/appsco-app.html
src/components/application/appsco-applications.html

https://appscoinc.atlassian.net/browse/DASH-3465

DASH-3465 [Policy] Personal dashboard not available even when policy is not turned on

---

src/components/integration/appsco-add-integration-rule.html
src/components/integration/appsco-edit-integration-rule.html

https://appscoinc.atlassian.net/browse/DASH-3456

DASH-3456 [Provisioning] Polishing of the offered options

---

src/components/integration/appsco-integration-rule-item.html

https://appscoinc.atlassian.net/browse/DASH-3463

DASH-3463 [Provisioning] Add Lookup on AppsCo as RA

---

src/components/application/company/appsco-company-resource-settings.html

https://appscoinc.atlassian.net/browse/DASH-3478

DASH-3478 [Frontend][Manage resource] Add Provisioning support drop-down to Resource settings

---

src/auditlog/appsco-audit-log.html
src/auditlog/data/locales.json
src/components/components/data/event-types.json

https://appscoinc.atlassian.net/browse/DASH-3494

DASH-3494 [Audit Log] Log Resource admin added and removed events to Audit Log

---

polymer.json
src/appsco-access-on-boarding-page.html
src/appsco-app.html
src/components/access-on-boarding/appsco-access-on-boarding-actions.html
src/components/access-on-boarding/appsco-access-on-boarding-event-item.html
src/components/access-on-boarding/appsco-access-on-boarding-page-actions.html
src/components/access-on-boarding/appsco-access-on-boarding-page-filters.html
src/components/access-on-boarding/appsco-access-on-boarding-roles-item.html
src/components/access-on-boarding/appsco-access-on-boarding-roles.html
src/components/access-on-boarding/data/event-types.json
src/components/components/appsco-list-behavior.html

https://appscoinc.atlassian.net/browse/DASH-3481

DASH-3481 [Frontend][Access On-boarding] Create Access On-boarding page

---

src/auditlog/appsco-audit-log.html
src/auditlog/data/locales.json

https://appscoinc.atlassian.net/browse/DASH-3480

DASH-3480 Log Access Onboarding events resolved to Audit Log

---

src/applications/appsco-manage-application-components-page.html
src/appsco-app.html
src/appsco-manage-resource-page.html
src/appsco-resources-page.html
src/components/application/company/appsco-company-resource-item.html
src/components/application/company/appsco-company-resources.html
src/components/components/appsco-api.html

https://appscoinc.atlassian.net/browse/DASH-3490

DASH-3490 [Frontend][Resources] Resource admin access to Resources page

---

src/appsco-app.html
src/appsco-manage-account-page.html
src/components/resource/appsco-add-resource-to-resource-admin.html
src/components/resource/appsco-resource-list-item.html
src/directory/appsco-directory-role-resource-admin-application.html
src/directory/appsco-directory-role-resource-admin-applications-page.html
src/directory/appsco-directory-role-resource-admin-applications.html
src/directory/appsco-manage-account-components-page.html

https://appscoinc.atlassian.net/browse/DASH-3492

DASH-3492 [Frontend][Manage Account] Create Resource admin card on manage account

---

src/appsco-app.html
src/appsco-manage-account-page.html
src/directory/appsco-manage-account-components-page.html
src/directory/appsco-manage-account-page-actions.html

https://appscoinc.atlassian.net/browse/DASH-3493

DASH-3493 [Frontend] Add Advanced settings to Manage resource and Manage account

---

src/appsco-app.html
src/components/access-on-boarding/data/event-types.json
src/components/account/appsco-account-image.html
src/components/application/appsco-application-info.html
src/components/resource/appsco-add-resource-admin.html

https://appscoinc.atlassian.net/browse/DASH-3504

DASH-3504 Appsco v2.2.11 pre release testing issues

---

src/appsco-app.html

https://appscoinc.atlassian.net/browse/DASH-3505

DASH-3505 [Frontend] Bulk actions are not shown after selecting resource on resources page

---

src/components/access-on-boarding/appsco-access-on-boarding-page-filters.html
src/components/components/appsco-search.html

https://appscoinc.atlassian.net/browse/DASH-3506

DASH-3506 [Frontend] Error in console on access on boarding page

---

src/components/application/appsco-application-analytics-security.html

https://appscoinc.atlassian.net/browse/DASH-3507

DASH-3507 [Frontend] Error after sharing resource on company resources page

---

src/components/access-on-boarding/appsco-access-on-boarding-roles.html
src/components/components/appsco-list-behavior.html

https://appscoinc.atlassian.net/browse/DASH-3528

DASH-3528 Access on-boarding text when the page is empty

---

src/billing/appsco-billing-send-invoice.html

https://appscoinc.atlassian.net/browse/DASH-3532

DASH-3532 [Billing] Investigate where the invoice email is sent

---

src/appsco-app-header.html
src/appsco-app.html
src/components/components/appsco-api.html
src/components/get-started/appsco-tutorial.html

https://appscoinc.atlassian.net/browse/DASH-3516

DASH-3516 [Frontend] Create global component appsco-tutorial

---

src/appsco-app.html
src/appsco-home-page.html
src/components/application/appsco-application-actions.html
src/components/application/appsco-applications.html

https://appscoinc.atlassian.net/browse/DASH-3496

DASH-3496 [Frontend] Get back the Personal dashboard filters

---

src/upgrade/appsco-upgrade-action.html

https://appscoinc.atlassian.net/browse/DASH-3537

DASH-3537 [Frontend] Add spaces in text on appsco business subscription dialog

---

index.html
polymer.json
src/appsco-app.html
src/appsco-get-started-page.html
src/components/get-started/appsco-tutorial-behaviour.html
src/components/get-started/appsco-tutorial-card.html
src/components/get-started/appsco-tutorial-company-branding.html
src/components/get-started/appsco-tutorial-company-settings.html
src/components/get-started/appsco-tutorial-progress.html
src/components/get-started/appsco-tutorial.html

https://appscoinc.atlassian.net/browse/DASH-3514

DASH-3514 [Frontend] Create Getting started page

---

src/applications/appsco-manage-application-components-page.html
src/applications/appsco-manage-resource-page-actions.html
src/appsco-app.html
src/appsco-manage-resource-page.html
src/components/application/appsco-application-actions.html

https://appscoinc.atlassian.net/browse/DASH-3541

DASH-3541 [Frontend] Advanced settings missing on Manage Resource page

---

index.html
src/appsco-app.html
src/appsco-get-started-page.html
src/company/appsco-company-branded-login-page.html
src/company/appsco-company-components-page.html
src/components/get-started/appsco-tutorial-behaviour.html
src/components/get-started/appsco-tutorial-branded-login.html
src/components/get-started/appsco-tutorial-card.html
src/components/get-started/appsco-tutorial-company-settings.html
src/components/get-started/appsco-tutorial.html

https://appscoinc.atlassian.net/browse/DASH-3531

DASH-3531 [Frontend] 3. Branded login - Set customized login for your company

---

src/appsco-app.html
src/components/get-started/appsco-tutorial-add-company-user.html
src/components/get-started/appsco-tutorial.html
src/directory/appsco-directory-add-account.html

https://appscoinc.atlassian.net/browse/DASH-3520

DASH-3520 [Frontend] 4. Directory - Add company users to directory

---

src/appsco-app.html
src/components/application/appsco-application-actions.html
src/components/components/appsco-cover-behaviour.html
src/components/get-started/appsco-tutorial-behaviour.html
src/components/get-started/appsco-tutorial-resources.html
src/components/get-started/appsco-tutorial.html

https://appscoinc.atlassian.net/browse/DASH-3519

DASH-3519 [Frontend] 5. Resources - Add company applications

---

src/appsco-app.html
src/components/components/appsco-cover-behaviour.html
src/components/get-started/appsco-tutorial-behaviour.html
src/components/get-started/appsco-tutorial-share-resources.html
src/components/get-started/appsco-tutorial.html
src/components/resource/appsco-share-resource.html

https://appscoinc.atlassian.net/browse/DASH-3521

DASH-3521 [Frontend] 6. Share resources - Share resources to users

---

src/applications/appsco-manage-application-components-page.html
src/appsco-manage-resource-page.html
src/components/application/appsco-application-groups.html

https://appscoinc.atlassian.net/browse/DASH-3540

DASH-3540 [Frontend] Groups card endless loading

---

src/company/appsco-company-components-page.html
src/company/appsco-company-idp-domain-item.html
src/company/appsco-company-idp-settings-page.html
src/components/get-started/appsco-tutorial-identity-provider.html
src/components/get-started/appsco-tutorial.html

https://appscoinc.atlassian.net/browse/DASH-3523

DASH-3523 [Frontend] 8. Identity Provider - set up an external identity provider

---

src/appsco-app.html
src/company/appsco-company-branded-login-page.html
src/company/appsco-company-domains-page.html
src/components/get-started/appsco-tutorial-behaviour.html
src/components/get-started/appsco-tutorial-card.html
src/components/get-started/appsco-tutorial-provisioning.html
src/components/get-started/appsco-tutorial.html
src/components/header/appsco-header-account-actions.html

https://appscoinc.atlassian.net/browse/DASH-3524

DASH-3524 [Frontend] 9. Provisioning - Add integrations with other systems

---

src/appsco-app.html
src/components/account/appsco-account-settings.html

https://appscoinc.atlassian.net/browse/DASH-3565

DASH-3565 [Frontend] Add default company page drop-down to account settings

---

src/appsco-app.html
src/components/application/company/appsco-company-resource-item.html
src/components/application/company/appsco-company-resource-settings-dialog.html

https://appscoinc.atlassian.net/browse/DASH-3561

DASH-3561 Add quick edit option to resources cards

---

src/appsco-app.html
src/appsco-resources-page.html
src/components/application/company/appsco-company-resource-item.html
src/components/application/company/appsco-company-resources.html

https://appscoinc.atlassian.net/browse/DASH-3566

DASH-3566 [Frontend] Enable grid view on Resources page

---

src/components/page/appsco-page-config-dropdown.html

https://appscoinc.atlassian.net/browse/DASH-3562

DASH-3562 Create page setup option on Resources

---

src/appsco-app.html

https://appscoinc.atlassian.net/browse/DASH-3570

DASH-3570 [Frontend] Error when adding or removing directory user

---

src/appsco-resources-page.html
src/components/application/company/appsco-company-resource-item.html
src/components/application/company/appsco-company-resources.html

https://appscoinc.atlassian.net/browse/DASH-3572

DASH-3572 [Frontend] Grid view on Resources page stacking icons vertically - Firefox	

---

src/appsco-resources-page.html

https://appscoinc.atlassian.net/browse/DASH-3571

DASH-3571 [Frontend] Bug when switching companies

---

src/components/application/appsco-application-actions.html

https://appscoinc.atlassian.net/browse/DASH-3597

DASH-3597 [Personal] Add application and dashboard filters not showing

---

src/components/resource/appsco-share-resource.html

https://appscoinc.atlassian.net/browse/DASH-3574

DASH-3574 Search by email in Share resource dialog

---

src/auditlog/appsco-audit-log.html

https://appscoinc.atlassian.net/browse/DASH-3542

DASH-3542 AppsCo Audit page

---

src/appsco-app.html

https://appscoinc.atlassian.net/browse/DASH-3624

DASH-3624 Console error when removing resource admin

---

src/appsco-manage-resource-page.html
src/appsco-resources-page.html

https://appscoinc.atlassian.net/browse/DASH-3623

DASH-3623 Removing group from resource results in error

---

src/appsco-resources-page.html

https://appscoinc.atlassian.net/browse/DASH-3619

DASH-3619 Adding group using create group button on groups page results in console error

---

src/applications/appsco-application-compliance-page.html

https://appscoinc.atlassian.net/browse/DASH-3621

DASH-3621 Current compliance info is not shown in dialog for company resource

---

src/applications/appsco-manage-application-components-page.html

https://appscoinc.atlassian.net/browse/DASH-3622

DASH-3622 Error when turning on auto login

---

src/appsco-app.html
src/appsco-resource-page.html

https://appscoinc.atlassian.net/browse/DASH-3617

DASH-3617 Reloading page on https://my-dev.appsco.com/resource/<resourceId> results in 404

---

src/components/application/appsco-application-settings.html
src/components/application/company/appsco-company-application-add-settings.html
src/components/application/company/appsco-company-resource-settings.html

https://appscoinc.atlassian.net/browse/DASH-3632

DASH-3632 Application URL verification - it should be possible to add IP address as URL

---

src/components/policy/data/policy-info.json

https://appscoinc.atlassian.net/browse/DASH-3602

DASH-3602 [Backend][Policy] Certification expires notification

---

src/appsco-manage-integration-page.html

https://appscoinc.atlassian.net/browse/DASH-3611

DASH-3611 Provisioning text overlap

---

src/appsco-app.html
src/appsco-dashboard-folder-page.html
src/appsco-home-page.html
src/appsco-resources-page.html

https://appscoinc.atlassian.net/browse/DASH-3616

DASH-3616 [Personal] Share and Edit buttons do not work on resources inside dashboard folders

---

src/applications/appsco-resources-page-actions.html
src/appsco-app.html
src/appsco-resources-page.html
src/components/page/appsco-content.html
src/components/page/appsco-manage-page-styles.html
src/components/page/appsco-page-global.html
src/components/page/appsco-page-styles.html

https://appscoinc.atlassian.net/browse/DASH-3604

DASH-3604 [Frontend][Resources] Create additional options section

---

src/application/appsco-resource-image-settings.html
src/appsco-manage-resource-page.html
src/appsco-resource-page.html
src/company/appsco-company-brand-settings.html
src/company/appsco-company-branded-login-page.html
src/company/appsco-company-image-settings.html
src/components/account/appsco-account-image-settings.html
src/components/components/appsco-image-upload.html
src/components/components/appsco-upload-image-behavior.html
src/components/components/appsco-upload-image-styles.html

https://appscoinc.atlassian.net/browse/DASH-3612

DASH-3612 [Frontend] Add Remove button to images in AppsCo

---

src/company/appsco-company-settings.html

https://appscoinc.atlassian.net/browse/DASH-3596

DASH-3596 Notify admin about new users and contacts

---

src/appsco-resources-page.html

https://appscoinc.atlassian.net/browse/DASH-3629

DASH-3629 [Frontend] Resource filter when selecting a group with is no resources assigned

---

polymer.json
src/appsco-additional-options-page.html
src/appsco-app-header.html
src/appsco-app.html
src/components/additional-options/appsco-additional-options-components-page.html
src/components/additional-options/appsco-additional-options-page-actions.html
src/components/additional-options/appsco-integration-resource-item.html
src/components/additional-options/appsco-integration-resources.html
src/components/additional-options/appsco-manage-idp-page.html
src/components/components/appsco-list-behavior.html
src/components/resource/appsco-idp-resource-add.html

https://appscoinc.atlassian.net/browse/DASH-3605

DASH-3605 [Frontend][Additioal options] Create Additional options page and implement actions

---

src/components/page/appsco-page-config-dropdown.html

https://appscoinc.atlassian.net/browse/DASH-3606

DASH-3606 [Frontend][Resources] Change title of toggle button on page settings dialog

---

src/appsco-app.html
src/components/application/appsco-application-actions.html
src/components/resource/appsco-share-resource.html

https://appscoinc.atlassian.net/browse/DASH-3545

DASH-3545 [Frontend] Move sharing to groups under share resource

---

src/components/combo-box/suggestion-combo-box.html
src/components/integration/appsco-add-integration-rule.html
src/components/integration/appsco-edit-integration-rule.html

https://appscoinc.atlassian.net/browse/DASH-3615

DASH-3615 [Provisioning] To be investigated: show existing groups in the drop-down menu in provisioning

---

src/components/resource/appsco-share-resource.html

https://appscoinc.atlassian.net/browse/DASH-3545

DАSH-3545 Loader stuck after share fixed

---

src/components/additional-options/appsco-additional-options-components-page.html

https://appscoinc.atlassian.net/browse/DASH-3605

DASH-3605 Console error fixed

---

src/appsco-app.html

https://appscoinc.atlassian.net/browse/DASH-3616

DАSH-3616 Breadcrumbs action fixed

---

src/appsco-groups-page.html

https://appscoinc.atlassian.net/browse/DASH-3653

DASH-3653 [Front end][Groups] Refresh not working when removing resource from the group

---

src/appsco-app.html
src/components/header/appsco-header-account-actions.html
src/components/header/appsco-header.html

https://appscoinc.atlassian.net/browse/DASH-3651

DASH-3651 Tutorial icon appears even when user has no company

---

src/components/components/data/appsco-api-errors.json
src/components/customer/appsco-customer-subscription-toggle.html

https://appscoinc.atlassian.net/browse/DASH-3339

DASH-3339 [Investigate] Number of licences calculation issue

---

src/components/account/appsco-account-log.html

https://appscoinc.atlassian.net/browse/DASH-3650

DASH-3650 Console error on My account page

---

src/appsco-directory-page.html
src/directory/appsco-info-dropdown.html

https://appscoinc.atlassian.net/browse/DASH-3648

DASH-3648 [Directory] Domain not verified info showing even when the domain is verified

---

src/components/integration/appsco-add-integration-rule.html
src/components/integration/appsco-edit-integration-rule.html

https://appscoinc.atlassian.net/browse/DASH-3657

DASH-3657 [Frontend] Error when selecting PSO that has no preset filters defined

---

src/components/integration/appsco-integration-rules-operators.html

https://appscoinc.atlassian.net/browse/DASH-3646

DASH-3646 [Provisioning] Advanced - matching email

---

src/components/components/appsco-list-behavior.html

https://appscoinc.atlassian.net/browse/DASH-3636

DASH-3636 Bulk actions not working with search items

---

src/account/appsco-account-components-page.html
src/applications/appsco-manage-application-components-page.html
src/company/appsco-company-components-page.html
src/company/appsco-company-domains.html
src/company/appsco-company-idp-domains.html
src/components/account/appsco-account-authorized-apps.html
src/components/account/appsco-account-log.html
src/components/account/company/appsco-account-devices.html
src/components/account/company/appsco-account-groups.html
src/components/additional-options/appsco-additional-options-components-page.html
src/components/application/appsco-application-groups.html
src/components/application/company/appsco-application-assignees.html
src/components/application/company/appsco-resource-admins.html
src/components/contact/appsco-contact-groups.html
src/components/contact/appsco-manage-contact-components-page.html
src/components/customer/appsco-customer-partner-admins.html
src/components/customer/appsco-manage-customer-components-page.html
src/components/group/appsco-company-group-contacts.html
src/components/group/appsco-company-group-resources.html
src/components/group/appsco-company-group-roles.html
src/components/group/appsco-manage-group-components-page.html
src/components/integration/appsco-integration-webhooks-card.html
src/components/oauth-application/appsco-manage-oauth-application-components-page.html
src/components/page/appsco-layout-with-cards-styles.html
src/components/page/appsco-manage-page-styles.html
src/directory/appsco-directory-role-applications.html
src/directory/appsco-manage-account-components-page.html
src/provisioning/appsco-manage-integration-components-page.html

https://appscoinc.atlassian.net/browse/DASH-3656

DASH-3656 [Front end][Manage Customer] Cards placing when there are only two cards

---

src/components/components/data/appsco-api-errors.json

https://appscoinc.atlassian.net/browse/DASH-3666

DASH-3666 Existing contact added as user

---

src/components/account/appsco-account-log.html

https://appscoinc.atlassian.net/browse/DASH-3667

DASH-3667 [Backend] OAuth application authorized should show the title of the application in response

---

src/components/combo-box/suggestion-combo-box.html

https://appscoinc.atlassian.net/browse/DASH-3668

DASH-3668 [Frontend][Account] Download from Google Play and Apple Store buttons not showing

---

src/auditlog/appsco-audit-log.html
src/auditlog/data/locales.json
src/components/components/data/event-types.json

https://appscoinc.atlassian.net/browse/DASH-3665

DASH-3665 [Frontend][Audit Log] Enable/Disable Policy not showing in Audit Log

---

src/components/contact/appsco-contact-applications.html

https://appscoinc.atlassian.net/browse/DASH-3693

DASH-3693 [Frontend][Manage Contact] When switching between contacts/users the number of shared resources is not refreshed

---

src/appsco-manage-integration-page.html
src/components/components/appsco-list-behavior.html
src/components/integration/appsco-integration-templates.html
src/provisioning/appsco-manage-integration-components-page.html

https://appscoinc.atlassian.net/browse/DASH-3690

DASH-3690 [Frontend][Manage Integration] Info section on Manage Integration page

---

src/appsco-app.html
src/appsco-manage-integration-page.html
src/appsco-provisioning-page.html
src/components/components/appsco-list-item-behavior.html
src/components/components/appsco-list-item-styles.html
src/components/integration/appsco-integration-template-item.html
src/components/integration/appsco-integration-templates.html
src/components/integration/data/integration-template-descriptions.json

https://appscoinc.atlassian.net/browse/DASH-3691

DASH-3691 [Frontend][Manage Integration] List use-cases for Gsuite integration and implement actions

---

src/components/integration/appsco-integration-webhook-item.html
src/components/integration/appsco-integration-webhooks.html
src/provisioning/appsco-integration-form.html

https://appscoinc.atlassian.net/browse/DASH-3675

DASH-3675 [Provisioning] Integration with BambooHR

---

src/components/integration/appsco-integration-rule-item.html

https://appscoinc.atlassian.net/browse/DASH-3727

DASH-3727 [Frontend][Provisioning] Run button should be displayed only for Lookup recipes

---

src/components/integration/data/integration-template-descriptions.json

https://appscoinc.atlassian.net/browse/DASH-3705

[DASH-3705] Title added to template

---

src/appsco-manage-integration-page.html

https://appscoinc.atlassian.net/browse/DASH-3675

[DASH-3675][Manage Integration] Integration logo image

---

src/provisioning/appsco-active-integration-item.html

https://appscoinc.atlassian.net/browse/DASH-3747

DASH-3747 [Backend] Refresh token command errors Entity manager is closed

---

src/appsco-manage-integration-page.html

https://appscoinc.atlassian.net/browse/DASH-3746

DASH-3746 [Backend] Build integration with LDAP

---

src/appsco-app.html
src/appsco-provisioning-page.html
src/components/integration/appsco-integration-template-item.html
src/provisioning/appsco-active-integration-item.html
src/provisioning/appsco-active-integrations.html

https://appscoinc.atlassian.net/browse/DASH-3753

[DASH-3753] [Provisioning] Unable to deactivate integration

---

src/appsco-app.html

https://appscoinc.atlassian.net/browse/DASH-3757

[DASH-3757] Get started icon not showing after all tutorials have been completed

---

src/appsco-app.html

https://appscoinc.atlassian.net/browse/DASH-3774

DASH-3774 [Access On-Boarding] Access on-boarding report does not show the user which is removed and has resources where users are handled manually

---

src/components/application/company/appsco-company-resources.html

https://appscoinc.atlassian.net/browse/DASH-3772

DASH-3772 [Frontend][Alliance][Resources] Add total count on Resources page

---

src/appsco-billing-page.html
src/appsco-customer-billing-page.html
src/billing/appsco-update-subscription-action.html
src/components/customer/appsco-customer-subscription-toggle.html
src/components/customer/appsco-manage-customer-components-page.html

https://appscoinc.atlassian.net/browse/DASH-3736

DASH-3736 [Frontend][Manage Customer] Modify the text on Customer subscription card

---

src/appsco-company-page.html
src/company/appsco-company-idp-settings-form-behavior.html
src/company/appsco-company-idp-settings-openid-form.html
src/company/appsco-company-idp-settings-page.html
src/company/appsco-company-idp-settings-saml-form.html
src/company/appsco-company-idp-settings.html
src/company/appsco-company-manage-idp-settings-page.html
src/company/appsco-deactivate-idp-settings.html
src/shared-styles.html

https://appscoinc.atlassian.net/browse/DASH-3756

[DASH-3756] [Frontend][Company Settings] Modify IDP setup form to include BambooHR

---

src/components/integration/appsco-add-integration-rule.html
src/components/integration/appsco-edit-integration-rule.html

https://appscoinc.atlassian.net/browse/DASH-3759

DASH-3759 [Provisioning] List only available methods in rules drop-down

---

src/provisioning/appsco-integration-form.html

https://appscoinc.atlassian.net/browse/DASH-3781

DASH-3781 [Provisioning] The name of the external system missing on Integration settings

---

src/application/appsco-home-page-actions.html
src/applications/appsco-resources-page-actions.html
src/appsco-app.html
src/appsco-company-home-page.html
src/appsco-dashboard-folder-page.html
src/appsco-home-page.html
src/appsco-resources-page.html
src/company/appsco-company-home-page-actions.html
src/components/application/appsco-application-actions.html
src/components/application/appsco-application-item.html
src/components/application/appsco-applications.html
src/components/application/company/appsco-company-resource-item.html
src/components/application/company/appsco-company-resources.html
src/components/components/appsco-list-behavior.html
src/components/components/appsco-list-item-styles.html
src/components/components/appsco-list-styles.html
src/components/page/appsco-page-config-dropdown.html

https://appscoinc.atlassian.net/browse/DASH-3778
https://appscoinc.atlassian.net/browse/DASH-3779

DASH-3778 and DASH-3779: List and grid view plus sort options on Home and Company Home

---

src/applications/appsco-resources-page-actions.html
src/appsco-app.html
src/appsco-resources-page.html
src/components/application/appsco-application-actions.html
src/components/components/appsco-list-behavior.html
src/components/page/appsco-page-config-dropdown.html

https://appscoinc.atlassian.net/browse/DASH-3777

DASH-3777 [Frontend][Alliance][Resources] Sorting on Resources page

---

src/appsco-company-home-page.html
src/appsco-home-page.html
src/appsco-resources-page.html
src/components/application/appsco-applications.html
src/components/components/appsco-list-behavior.html
src/components/page/appsco-page-config-dropdown.html

https://appscoinc.atlassian.net/browse/DASH-3778

DASH-3778 and DASH-3779: Sorting option fixed

---

src/components/page/appsco-page-config-dropdown.html

https://appscoinc.atlassian.net/browse/DASH-3777
https://appscoinc.atlassian.net/browse/DASH-3779

DASH-3778 and DASH-3779: Sorting inverse fixed

---

src/auditlog/appsco-audit-log.html

https://appscoinc.atlassian.net/browse/DASH-3806

DASH-3806 [Policies] Unable to remove Disapprove personal dashboard policy

---

src/appsco-app-header.html
src/appsco-app.html
src/auditlog/appsco-audit-log.html
src/components/components/appsco-behavior-export-report.html
src/components/components/data/appsco-api-errors.json
src/components/integration/appsco-integration-settings.html
src/components/integration/appsco-run-integration-force-sync.html
src/provisioning/appsco-add-integration-form.html
src/provisioning/appsco-integration-form.html
src/provisioning/appsco-manage-integration-page-actions.html

https://appscoinc.atlassian.net/browse/DASH-3803

DASH-3803 [Frontend][Provisioning] Add Force sync option

---

src/components/application/appsco-application-actions.html

https://appscoinc.atlassian.net/browse/DASH-3800

DASH-3800 [Frontend][Dashboard] Page settings icon color

---

src/components/policy/appsco-ip-whitelist-policy-settings.html

https://appscoinc.atlassian.net/browse/DASH-3816

DASH-3816 Test and cleanup AppsCo for Symfony 4 upgrade

---

src/appsco-company-home-page.html
src/appsco-contact-home-page.html
src/appsco-home-page.html
src/appsco-resource-page.html
src/components/application/appsco-application-item.html

https://appscoinc.atlassian.net/browse/DASH-3817

DASH-3817 [Frontend][Dashboard] Share button does not react on first click

---

src/appsco-policies-report-page.html
src/components/components/appsco-list-behavior.html
src/components/report/appsco-policy-report-roles.html

https://appscoinc.atlassian.net/browse/DASH-3822

DASH-3822 [Frontend][Policies report] Modify text on policies report when there are no broken policies

---

src/appsco-app.html
src/appsco-contact-home-page.html
src/company/appsco-contact-home-page-actions.html

https://appscoinc.atlassian.net/browse/DASH-3823

DASH-3823 [Frontend][Dashboard] Page settings on company dashboard

---

src/components/access-on-boarding/appsco-access-on-boarding-roles-item.html

https://appscoinc.atlassian.net/browse/DASH-3824

DASH-3824 [Frontend][Access Onboarding] Change button text

---

src/appsco-statistics-page.html

https://appscoinc.atlassian.net/browse/DASH-3830

DASH-3830 [Frontend][Statistics] Add support for tracking application usage for contacts

---

src/appsco-app.html

https://appscoinc.atlassian.net/browse/DASH-3831

DASH-3831 [Audit log] Copy credentials log not logged in resource or audit log

---

src/components/policy/appsco-enforce-two-factor-policy-settings.html
src/components/policy/appsco-policy-settings.html

https://appscoinc.atlassian.net/browse/DASH-3813

DASH-3813 [Policy] Expand 2fa policy with IP whitelist option

---

src/components/application/appsco-application-log.html

https://appscoinc.atlassian.net/browse/DASH-3847

DASH-3847 [Audit log] Copy credentials event should be logged in Resource log

---

src/appsco-app.html
src/appsco-company-home-page.html
src/appsco-company-page.html
src/company/appsco-company-brand-settings-page.html
src/company/appsco-company-brand-settings.html
src/company/appsco-company-dashboard-image-settings.html

https://appscoinc.atlassian.net/browse/DASH-3844

DASH-3844 [Business Systems Consulting] Logo watermark on the Company Dashboard background

---

src/appsco-statistics-page.html

https://appscoinc.atlassian.net/browse/DASH-3851

DASH-3851 [Statistics] Application usage statistics example not showing

---

src/components/application/appsco-applications.html
src/components/components/appsco-list-behavior.html

https://appscoinc.atlassian.net/browse/DASH-3852

DASH-3852 [Frontend] Load more button issue

---

src/application/appsco-resource-image-settings.html

https://appscoinc.atlassian.net/browse/DASH-3858

DASH-3858 [Resources] Unable to upload icon image

---

src/company/appsco-company-idp-settings-openid-form.html

https://appscoinc.atlassian.net/browse/DASH-3877

DASH-3877 [Backend] Create pure OpenID integration

---

src/billing/appsco-credit-card.html
src/billing/appsco-update-subscription-action.html
src/upgrade/appsco-upgrade-action.html

https://appscoinc.atlassian.net/browse/DASH-3866

DASH-3866 Add support for SCA flow during initial subscription creation

---

src/billing/appsco-credit-card.html

https://appscoinc.atlassian.net/browse/DASH-3864

DASH-3864 Upgrade stripe client-side API to v3.0

---

src/company/appsco-company-domains.html

https://appscoinc.atlassian.net/browse/DASH-3856

DASH-3856 [Company Settings] Hide number of unverified domains if there are none

---

src/components/integration/appsco-add-integration-rule.html
src/components/integration/appsco-edit-integration-rule.html

https://appscoinc.atlassian.net/browse/DASH-3859

DASH-3859 [Provisioning] Add available groups drop-down to advanced settings

---

src/company/appsco-company-idp-settings-openid-form.html

https://appscoinc.atlassian.net/browse/DASH-3878

DASH-3878 [BambooHR] Remove Client ID and Client Secret fields from BambooHR IdP settings

---

src/applications/appsco-manage-application-components-page.html
src/appsco-manage-resource-page.html
src/company/appsco-company-idp-settings-openid-form.html
src/components/application/appsco-application-form-open-id.html
src/components/application/company/appsco-company-application-add-settings.html
src/components/application/company/appsco-company-resource-settings.html

https://appscoinc.atlassian.net/browse/DASH-3879

DASH-3879 [Clearsense] Implement support for OpenID as IDP

---

src/appsco-manage-resource-page.html
src/components/application/appsco-application-form-open-id.html

https://appscoinc.atlassian.net/browse/DASH-3884

DASH-3884 [OpenID] Add discovery route and expand OpenID resource settings with entity id field

---

src/components/application/appsco-application-add-search.html
src/components/application/company/appsco-company-application-add-search.html

https://appscoinc.atlassian.net/browse/DASH-3882

DASH-3882 [Dashboard][Frontend] Add custom application link should be visible all the time

---

src/components/appsco-time-picker/appsco-time-picker.html
src/components/policy/appsco-login-time-restriction-policy-settings.html
src/components/policy/appsco-policy-settings.html
src/components/policy/data/timezone-list.json

DASH-3871 [Policy] Login time restriction policy

DASH-3871 [Policy] Login time restriction policy

---

src/appsco-app-header.html
src/appsco-app.html
src/company/appsco-company-idp-settings.html
src/components/components/data/appsco-api-errors.json
src/components/group/appsco-company-group-item.html
src/components/group/appsco-company-rename-group.html

https://appscoinc.atlassian.net/browse/DASH-3886

DASH-3886 Rename group option

---

src/components/application/appsco-application-details-unpw.html

https://appscoinc.atlassian.net/browse/DASH-3901

DASH-3901 Copy password in resource info section missing

---

src/company/appsco-company-idp-settings.html
src/components/group/appsco-company-rename-group.html

https://appscoinc.atlassian.net/browse/DASH-3886

DASH-3886 Fixed rename group issue

---

index.html
polymer.json
src/appsco-groups-page.html
src/components/group/appsco-company-group-notification-dialog.html
src/components/header/appsco-account-notifications-dropdown.html
src/components/header/appsco-dropdown.html

https://appscoinc.atlassian.net/browse/DASH-3910

DASH-3910 Account, groups and notifications fix

---

polymer.json
src/appsco-additional-options-page.html
src/appsco-app.html
src/components/additional-options/appsco-manage-idp-page.html
src/components/resource/appsco-idp-resource-add.html

https://appscoinc.atlassian.net/browse/DASH-3910

DASH-3910 Additional settings fix

---

src/appsco-app.html
src/components/page/appsco-content.html

https://appscoinc.atlassian.net/browse/DASH-3910

DASH-3910 Added passive listeners in Appsco app

---

package.json

https://appscoinc.atlassian.net/browse/DASH-3913

DASH-3913 Vaadin disable statistics

---

package-lock.json
package.json
src/account/appsco-account-log-page.js
src/application/appsco-application-log-page.js
src/applications/appsco-application-compliance-page.js
src/applications/appsco-manage-application-components-page.js
src/appsco-audit-log-page.js
src/appsco-statistics-page.js
src/components/application/company/appsco-company-application-add-search.js
src/components/page/appsco-page-global.js
src/directory/appsco-directory-role-applications.js
src/directory/appsco-manage-account-components-page.js

DASH-3915 Fixed empty event type list issue

---

src/components/account/appsco-account-log.js
src/components/application/appsco-application-item.js
src/components/application/appsco-applications.js
src/directory/appsco-directory-role-applications.js
src/directory/appsco-directory-role-resource-admin-applications.js

DASH-3915 Fixed account log and resource admin card

---

index.html
src/application/appsco-application-settings-dialog.js
src/application/appsco-dialog-application-add.js
src/application/appsco-home-page-actions.js
src/appsco-app-header.js
src/appsco-app.js
src/appsco-home-page.js
src/components/application/appsco-application-add.js
src/components/application/appsco-application-revoke.js
src/components/application/appsco-application-share.js
src/components/application/appsco-applications.js
src/components/application/company/appsco-company-resource-settings-dialog.js
src/components/folder/appsco-add-folder.js
src/components/folder/appsco-folders-application-add.js
src/components/folder/appsco-folders-remove.js
src/components/folder/appsco-folders-rename.js
src/components/get-started/appsco-tutorial-add-company-user.js
src/components/get-started/appsco-tutorial-branded-login.js
src/components/get-started/appsco-tutorial-card.js
src/components/get-started/appsco-tutorial-company-branding.js
src/components/get-started/appsco-tutorial-company-domain.js
src/components/get-started/appsco-tutorial-company-settings.js
src/components/get-started/appsco-tutorial-identity-provider.js
src/components/get-started/appsco-tutorial-provisioning.js
src/components/get-started/appsco-tutorial-resources.js
src/components/get-started/appsco-tutorial-share-resources.js
src/components/get-started/appsco-tutorial.js
src/components/header/appsco-account-info.js
src/components/header/appsco-brand.js

DASH-3915 Performance tuning

---

src/application/appsco-dialog-application-add.js
src/appsco-app.js
src/appsco-company-home-page.js
src/appsco-home-page.js
src/components/application/appsco-application-add-settings.js
src/components/application/appsco-application-settings.js
src/components/application/appsco-applications.js
src/components/folder/appsco-folders-remove.js
src/components/folder/appsco-folders-rename.js

DASH-3915 Polymer 3 fixes

---

src/appsco-app.js
src/components/page/appsco-content.js

DASH-3915 Drawer animation performance improvement

---

src/appsco-app.js
src/appsco-company-home-page.js

DASH-3915 Fixed company home page empty apps loader

---

src/applications/appsco-application-compliance-page.js

https://appscoinc.atlassian.net/browse/DASH-3906

DASH-3906 Fixed typo

---

src/components/account/appsco-account-authorized-apps.js

https://appscoinc.atlassian.net/browse/DASH-3929

DASH-3929 Fixed OAuth applications load more issue

---

src/appsco-manage-integration-page.js

https://appscoinc.atlassian.net/browse/DASH-3923

DASH-3923 Fixed undefined call on iron-image

---

src/components/integration/appsco-integration-webhooks.js

https://appscoinc.atlassian.net/browse/DASH-3924

DASH-3924 Fixed issue with un/registering webhooks

---

src/appsco-customers-page.js
src/appsco-resources-page.js

https://appscoinc.atlassian.net/browse/DASH-3922

DASH-3922 Fixed dialog triggering forever loading progress

---

src/appsco-app.js
src/appsco-contacts-page.js
src/appsco-directory-page.js
src/appsco-groups-page.js
src/appsco-resources-page.js
src/components/group/appsco-delete-groups.js

https://appscoinc.atlassian.net/browse/DASH-3920

DASH-3920 Fixed group modify not updating issue

---

src/account/appsco-account-page-actions.js
src/applications/appsco-manage-resource-page-actions.js
src/appsco-account-page.js
src/appsco-app.js
src/appsco-company-account-page.js
src/appsco-manage-account-page.js
src/appsco-manage-resource-page.js
src/company-account/appsco-company-account-page-actions.js
src/components/account/appsco-account-actions.js
src/directory/appsco-manage-account-page-actions.js

https://appscoinc.atlassian.net/browse/DASH-3930

DASH-3930 Fixed Advanced settings behaviour

---

src/appsco-home-page.js

https://appscoinc.atlassian.net/browse/DASH-3926

DASH-3926 Fixed home page revoke and manage dialog issue

---

src/application/appsco-application-components-page.js
src/applications/appsco-company-resource-settings-page.js
src/applications/appsco-manage-application-components-page.js
src/appsco-manage-group-page.js
src/appsco-resource-page.js
src/components/application/company/appsco-company-resource-settings.js
src/components/group/appsco-group-contacts-page.js
src/components/group/appsco-group-roles-page.js

DASH-3915 Fixed padding and empty object check bug

---

src/appsco-app.js

https://appscoinc.atlassian.net/browse/DASH-3925

DASH-3925 Fixed remove from group contacts page console error

---

src/applications/appsco-resource-admins-page.js
src/appsco-manage-account-page.js
src/appsco-manage-resource-page.js
src/components/resource/appsco-add-resource-admin.js
src/components/resource/appsco-add-resource-to-resource-admin.js
src/directory/appsco-directory-role-resource-admin-applications.js

https://appscoinc.atlassian.net/browse/DASH-3927

DASH-3927 Fixed add resource admin dialog issues

---

src/appsco-contacts-page.js

https://appscoinc.atlassian.net/browse/DASH-3933

DASH-3933 Fixed progress bar and load more location issue

---

src/appsco-manage-customer-page.js
src/components/customer/appsco-add-partner-admin.js
src/components/customer/appsco-customer-partner-admins-page.js

https://appscoinc.atlassian.net/browse/DASH-3942

DASH-3942 Fixed dialog progress and header padding

---

src/application/appsco-application-settings-page.js
src/application/appsco-application-subscribers-page.js

https://appscoinc.atlassian.net/browse/DASH-3939

DASH-3939 Added missing padding

---

src/appsco-billing-page.js
src/appsco-customer-billing-page.js

https://appscoinc.atlassian.net/browse/DASH-3940

DASH-3940 Added styling to Send invoice button

---

src/appsco-dashboard-folder-page.js

https://appscoinc.atlassian.net/browse/DASH-3941

DASH-3941 Fixed dashboard folder reenter behaviour

---

src/application/appsco-application-components-page.js
src/appsco-resource-page.js
src/components/application/appsco-application-autologin.js

https://appscoinc.atlassian.net/browse/DASH-3937

DASH-3937 Fixed Auto Login behaviour issues

---

src/appsco-app.js

https://appscoinc.atlassian.net/browse/DASH-3934

DASH-3934 Fixed bad ACL call

---

src/appsco-app.js

https://appscoinc.atlassian.net/browse/DASH-3918

DASH-3918 Fixed selected company chooser

---

src/appsco-app.js

https://appscoinc.atlassian.net/browse/DASH-3959

DASH-3959 Fixed issue with changing company when settings saved

---

src/appsco-app.js
src/appsco-dashboard-folder-page.js

https://appscoinc.atlassian.net/browse/DASH-3909

DASH-3961 Fixed dashboard-folder redirect and wrong api issue

---

src/company/appsco-company-dashboard-image-settings.js
src/company/appsco-company-image-settings.js
src/components/components/appsco-image-upload.js

https://appscoinc.atlassian.net/browse/DASH-3961

DASH-3961 Fixed bad image urls

---

src/components/resource/appsco-share-resource.js

https://appscoinc.atlassian.net/browse/DASH-3968

DASH-3968 Removed only managed users can be shared SSO apps limitation

---

src/appsco-manage-account-page.js
src/directory/appsco-manage-account-components-page.js

https://appscoinc.atlassian.net/browse/DASH-3947

DASH-3947 Fixed resource admin reloading

---

src/appsco-contacts-page.js

https://appscoinc.atlassian.net/browse/DASH-3917

DASH-3917 Added Edit button on Contacts page

---

src/appsco-contacts-page.js

https://appscoinc.atlassian.net/browse/DASH-3965

DASH-3965 Fixed Contacts page Info section

---

src/components/policy/appsco-policy-settings.js

https://appscoinc.atlassian.net/browse/DASH-3900

DASH-3900 Removed additional settings text in Time restriction policy

---

src/components/application/appsco-import-personal-resources.js
src/components/application/appsco-import-resources.js
src/components/application/data/example_resource_import.csv

https://appscoinc.atlassian.net/browse/DASH-3849

DASH-3849 Added import from Last Pass file example

---

src/company/appsco-company-domain-item.js

https://appscoinc.atlassian.net/browse/DASH-3967

DASH-3967 Fixed domain created and verified dates not showing

---

src/appsco-access-on-boarding-page.js
src/components/access-on-boarding/appsco-access-on-boarding-roles-item.js

https://appscoinc.atlassian.net/browse/DASH-3952

DASH-3952 Added resolved events to Access on boarding

---

src/appsco-access-on-boarding-page.js
src/appsco-app.js

https://appscoinc.atlassian.net/browse/DASH-3971

DASH-3971 Changed Access On Boarding to Access Tasks

---

src/appsco-app.js
src/appsco-home-page.js
src/components/application/appsco-application-actions.js
src/components/application/appsco-applications-label.js
src/components/application/appsco-applications-labels.js
src/components/application/appsco-applications.js
src/components/components/appsco-api.js
src/components/page/appsco-page-config-dropdown.js

https://appscoinc.atlassian.net/browse/DASH-3974

DASH-3974 Added group by origin option

---

src/components/application/appsco-applications-label.js

https://appscoinc.atlassian.net/browse/DASH-3985

DASH-3985 Change collapse state based on applications count

---

src/application/appsco-home-page-actions.js
src/components/application/appsco-application-actions.js
src/components/page/appsco-page-config-dropdown.js

https://appscoinc.atlassian.net/browse/DASH-3984

DASH-3984 Removed dropdown from anything but personal page

---

index.html
package-lock.json
package.json
src/appsco-app.js
src/appsco-home-page.js
src/components/application/appsco-application-actions.js
src/components/header/appsco-account-info.js
src/components/header/appsco-account-notifications-dropdown.js
src/components/header/appsco-dropdown.js
src/components/header/appsco-header-account-actions.js
src/components/page/appsco-page-config-dropdown.js

https://appscoinc.atlassian.net/browse/DASH-3991

DASH-3991 Updated Polymer to 3.4.1; Performance tuning

---

src/components/application/appsco-application-info.js

https://appscoinc.atlassian.net/browse/DASH-3990

DASH-3990 Fixed bad request for image

---

src/appsco-home-page.js
src/components/application/appsco-applications-labels.js
src/components/application/appsco-applications.js

https://appscoinc.atlassian.net/browse/DASH-3989

DASH-3989 Disabled inactive applications component

---

src/appsco-home-page.js
src/components/page/appsco-content.js

https://appscoinc.atlassian.net/browse/DASH-3996

DASH-3996 Fixed animation issue with info section

---

src/appsco-home-page.js

https://appscoinc.atlassian.net/browse/DASH-3995

DASH-3995 Fixed issue with adding/removing apps from homepage

---

src/appsco-app.js

https://appscoinc.atlassian.net/browse/DASH-3997

DASH-3997 Fixed removed resource not redirecting to homepage

---

src/appsco-app.js
src/appsco-customers-page.js

https://appscoinc.atlassian.net/browse/DASH-3991

DASH-3991 Performance tuning

---

src/application/appsco-resource-image-settings.js
src/components/folder/appsco-folders.js

https://appscoinc.atlassian.net/browse/DASH-4001

DASH-4001 Fixed issue with resource image

---

src/appsco-trybusiness-page.js
src/components/page/appsco-content.js

https://appscoinc.atlassian.net/browse/DASH-4004

DASH-4004 Fixed Info section flickering on Try Business page

---

src/application/appsco-home-page-actions.js
src/appsco-app.js
src/appsco-home-page.js
src/components/application/appsco-applications-label.js
src/components/application/appsco-applications-labels.js
src/components/application/appsco-home-page-applications.js
src/components/components/appsco-api.js
src/components/filter/appsco-filter-company-groups.js
src/components/group/appsco-company-group-item.js
src/components/group/appsco-company-groups.js
src/components/page/appsco-page-config-dropdown.js

https://appscoinc.atlassian.net/browse/DASH-4002

DASH-4002 Personal home navigation improvements

---

src/appsco-company-page.js

https://appscoinc.atlassian.net/browse/DASH-4010

DASH-4010 Added partner token

---

src/appsco-company-page.js

https://appscoinc.atlassian.net/browse/DASH-4017

DASH-4017 Fixed empty company settings page

---

src/components/account/appsco-account-settings.js

https://appscoinc.atlassian.net/browse/DASH-4018

DASH-4018 Added AppsCo One HR option to account settings default company page

---

src/appsco-app-header.js
src/appsco-app.js
src/components/components/appsco-api.js
src/components/header/appsco-header.js

https://appscoinc.atlassian.net/browse/DASH-4042

DASH-4042 Changed Try business button

---

src/company/appsco-company-settings.js
src/components/components/data/appsco-api-errors.json

https://appscoinc.atlassian.net/browse/AW-73

AW-73 Add company number registration on company

---

polymer.json
src/appsco-app.js
src/appsco-licences-page.js
src/components/components/appsco-list-behavior.js
src/components/licence/appsco-delete-licences.js
src/components/licence/appsco-licence-dialog.js
src/components/licence/appsco-licence-image.js
src/components/licence/appsco-licence-item.js
src/components/licence/appsco-licences-actions.js
src/components/licence/appsco-licences-page-actions.js
src/components/licence/appsco-licences.js

https://appscoinc.atlassian.net/browse/AW-74

AW-74 Licence provisioning and report

---

src/components/components/appsco-list-behavior.js

https://appscoinc.atlassian.net/browse/AW-99

AW-99 Fixed multiple items delete issue

---

src/appsco-app.js
src/appsco-licences-page.js
src/components/licence/appsco-import-licences-dialog.js
src/components/licence/appsco-licences-actions.js
src/components/licence/data/example-licences-import.csv

https://appscoinc.atlassian.net/browse/AW-74

AW-74 Import licences from CSV

---

src/components/access-on-boarding/appsco-access-on-boarding-roles-item.js

https://appscoinc.atlassian.net/browse/AW-104

AW-104 Hide resolved tasks in Access Task list

---

src/components/header/appsco-account-info.js
src/components/header/appsco-account-notifications-dropdown.js
src/components/header/appsco-header-account-actions.js

https://appscoinc.atlassian.net/browse/AW-112

AW-112 Notification and account dropdowns activate after a few clicks

---

src/components/group/appsco-company-group-item.js

https://appscoinc.atlassian.net/browse/AW-115

AW-115 [Personal Home] Too many requests to groups endpoints

---

src/appsco-directory-page.js
src/components/group/appsco-company-group-item.js
src/components/group/appsco-company-groups.js

https://appscoinc.atlassian.net/browse/AW-117

AW-117 Number of employees 

---

src/appsco-app.js
src/appsco-directory-page.js
src/components/group/appsco-company-group-item.js
src/directory/appsco-directory-summary.js

https://appscoinc.atlassian.net/browse/AW-120

AW-120 [Directory] Summary page

---

src/appsco-groups-page.js

https://appscoinc.atlassian.net/browse/AW-124

AW-124 [Groups] Remove setting default group on page load

---

src/components/application/appsco-applications-label.js
src/components/application/appsco-applications-labels.js
src/components/application/appsco-applications.js

https://appscoinc.atlassian.net/browse/AW-126

AW-126 CLS on personal home page when grouped by origin

---

src/appsco-manage-integration-page.js

https://appscoinc.atlassian.net/browse/AW-131

AW-131 [Manage integration] Fix issue with integration templates

---

src/components/application/appsco-applications.js

https://appscoinc.atlassian.net/browse/AW-175

AW-175 Fixed console error in applications list component

---

src/appsco-manage-integration-page.js
src/components/integration/appsco-integration-webhooks.js
src/provisioning/appsco-integration-webhooks-page.js

https://appscoinc.atlassian.net/browse/AW-159

AW-159 [Provisioning] Refresh webhooks page after adding template recipe

---

src/components/report/appsco-policy-report-page-filters.js

https://appscoinc.atlassian.net/browse/AW-179

AW-179 [Reports] Undefined property

---

src/components/application/appsco-application-info.js

https://appscoinc.atlassian.net/browse/AW-178

AW-178 [Resources] Console error 404 when the new app is created

---

src/company/appsco-company-settings.js

https://mesier.atlassian.net/browse/IPD-54

IPD-54 Add toggle to enable/disable all notification overrides

---

src/appsco-app.js

https://mesier.atlassian.net/browse/IPD-55

IPD-55 Fixed routing issue

---

src/company/appsco-company-settings.js

https://mesier.atlassian.net/browse/IPD-40

IPD-40 Email notifications toggle

---

src/appsco-app.js

https://appsco.atlassian.net/browse/HR-6139

HR-6139 Front end error on manage integration page

---

src/auditlog/appsco-audit-log.js
src/auditlog/data/locales.json

https://appsco.atlassian.net/browse/HR-6393

HR-6393 Added company subscription created event

---

src/appsco-manage-integration-page.js
src/provisioning/appsco-integration-form.js

https://appsco.atlassian.net/browse/HR-6898

HR-6898 Microsoft Entra integration
